export const Profile = ["Tronix", "Web Dev", "App Dev", "Algos"];

export const Year = [
  "All",
  "B Tech 4th year",
  "B Tech 3rd Year",
  "B Tech 2nd Year",
  "MCA 2nd year",
];

export const members = [
  {
    id: "1",
    Name: "Kishore",
    Photo: "images/Members/Kishore V.jpg",
    Profile: "Web Dev",
    Year: "B Tech 4th year",
    LinkedIn: "https://www.linkedin.com/in/kishore-v-a006ab153/",
    Github: "https://github.com/Kishorehere",
    Website: "",
  },
  {
    id: "2",
    Name: "S Raghul",
    Photo: "images/Members/Raghul Sivavenkatesh.jpg",
    Profile: "Web Dev",
    Year: "B Tech 4th year",
    LinkedIn: "https://www.linkedin.com/in/sraghul127",
    Github: "https://github.com/Raghul127",
    Website: "https://raghul127.github.io/",
  },
  {
    id: "3",
    Name: "P Naveena",
    Photo: "images/Members/Naveena.jpg",
    Profile: "Web Dev",
    Year: "B Tech 4th year",
    LinkedIn: "https://www.linkedin.com/in/na899",
    Github: "https://github.com/na899",
    Website: "",
  },
  {
    id: "4",
    Name: "Vishal Saranathan",
    Photo: "images/Members/Vishal Saranathan.jpg",
    Profile: "Web Dev",
    Year: "B Tech 4th year",
    LinkedIn: "https://www.linkedin.com/in/vishal-s-126000145/",
    Github: "https://github.com/VishalS99",
    Website: "",
  },

  {
    id: "5",
    Name: "Mohamed Sohail",
    Photo: "images/Members/Mohammed Sohail.jpg",
    Profile: "Web Dev",
    Year: "B Tech 4th year",
    LinkedIn: "https://www.linkedin.com/in/mohamedsohail/",
    Github: "https://github.com/kamikazechaser",
    Website: "https:kamikazechaser.github.io",
  },
  {
    id: "6",
    Name: "Prakhar Singh",
    Photo: "images/Members/Prakhar Singh.jpg",
    Profile: "Web Dev",
    Year: "B Tech 4th year",
    LinkedIn: "https://www.linkedin.com/in/prakhar-singh-852110173/",
    Github: "https://github.com/prakhar242",
    Website: "",
  },
  {
    id: "7",
    Name: "N Praveen Chandhar",
    Photo: "images/Members/N Praveen Chandhar.jpg",
    Profile: "Web Dev",
    Year: "B Tech 4th year",
    LinkedIn: "https://www.linkedin.com/in/praveen27/",
    Github: "https://github.com/gigatesseract/",
    Website: "https://gigatesseract.github.io/",
  },
  {
    id: "8",
    Name: "Joel Johnson",
    Photo: "images/Members/Joel Johnson.jpeg",
    Profile: "Web Dev",
    Year: "B Tech 4th year",
    LinkedIn: "https://www.linkedin.com/in/joel-johnson-36694015b/",
    Github: "https://github.com/quantum-jo",
    Website: "joeljohnson.me",
  },
  {
    id: "9",
    Name: "Kamalesh Palanisamy",
    Photo: "images/Members/Kamalesh Palanisamy.jpg",
    Profile: "Web Dev",
    Year: "B Tech 4th year",
    LinkedIn: "https://www.linkedin.com/in/kamalesh-palanisamy-2b5265149/",
    Github: "https://github.com/kamalesh0406",
    Website: "http://www.kamaleshp.com",
  },

  {
    id: "10",
    Name: "Anish C ",
    Photo: "images/Members/Chakkirala Anish.jpg",
    Profile: "Web Dev",
    Year: "B Tech 3rd Year",
    LinkedIn: "https://donothaveone.com",
    Github: "https://github.com/chakki1234",
    Website: "",
  },
  {
    id: "11",
    Name: "Anjaneya Tripathi",
    Photo: "images/Members/Anjaneya Tripathi.jpeg",
    Profile: "Web Dev",
    Year: "B Tech 3rd Year",
    LinkedIn: "https://www.linkedin.com/in/anjaneya-tripathi-610234183/",
    Github: "https://github.com/AnjaneyaTripathi",
    Website: "",
  },
  {
    id: "12",
    Name: "Thrishik Senthilkumar",
    Photo: "images/Members/Thrishik Senthilkumar.jpg",
    Profile: "Web Dev",
    Year: "B Tech 3rd Year",
    LinkedIn: "https://in.linkedin.com/in/thrishik-senthilkumar-123918176",
    Github: "https://github.com/thrishik7",
    Website: "",
  },
  {
    id: "13",
    Name: "Barath Kumar S",
    Photo: "images/Members/Barath.png",
    Profile: "Web Dev",
    Year: "B Tech 3rd Year",
    LinkedIn: "https://linkedin.com/in/barath1999",
    Github: "https://www.github.com/barath99",
    Website: "https://barath99.github.io",
  },
  {
    id: "14",
    Name: "Smrithi Prakash",
    Photo: "images/Members/Smrithi.png",
    Profile: "Web Dev",
    Year: "B Tech 3rd Year",
    LinkedIn: "https://linkedin.com/in/smrithi-prakash-452173193",
    Github: "https://github.com/Smrithi23",
    Website: "",
  },
  {
    id: "15",
    Name: "Jerry J",
    Photo: "images/Members/Jerry.png",
    Profile: "Web Dev",
    Year: "B Tech 3rd Year",
    LinkedIn: "https://www.linkedin.com/in/jerry-j-89aa52174/",
    Github: "https://github.com/Hank-learner",
    Website: "",
  },
  {
    id: "16",
    Name: "Amar Rokade",
    Photo: "images/Members/Amar Rokade.jpg",
    Profile: "Web Dev",
    Year: "B Tech 2nd Year",
    LinkedIn: "https://www.linkedin.com/in/amar-rokade-903a82184/",
    Github: "https://github.com/amar-rokade",
    Website: "",
  },
  {
    id: "17",
    Name: "Gokulraaj",
    Photo: "images/Members/Gokulraaj Vaithiyanathan.jpg",
    Profile: "Web Dev",
    Year: "B Tech 2nd Year",
    LinkedIn: "https://www.linkedin.com/in/gokulraaj-vaithiyanathan-a7b7781a5",
    Github: "https://github.com/gokul-00",
    Website: "https://im-gokul.netlify.app/",
  },
  {
    id: "18",
    Name: "Subramanian V V",
    Photo: "images/Members/Subramanian.jpg",
    Profile: "Web Dev",
    Year: "B Tech 2nd Year",
    LinkedIn: "https://www.linkedin.com/in/subramanian-v-v-85563a1a6",
    Github: "https://github.com/subramanian-vv",
    Website: "",
  },
  {
    id: "19",
    Name: "Mansi Bisen",
    Photo: "images/Members/Mansi Bisen.jpeg",
    Profile: "Web Dev",
    Year: "B Tech 2nd Year",
    LinkedIn: "https://www.linkedin.com/in/mansi-bisen-23a26118b",
    Github: "https://github.com/Mansibisen",
    Website: "",
  },
  {
    id: "20",
    Name: "Mohana Sundaram S",
    Photo: "images/Members/Mohana Sundaram.jpeg",
    Profile: "Web Dev",
    Year: "B Tech 2nd Year",
    LinkedIn: "https://www.linkedin.com/in/mohana-sundaram-s-90a458190/",
    Github: "https://github.com/highonweb",
    Website: "https://msundaram.me",
  },

  {
    id: "21",
    Name: "Tharun Kumaar",
    Photo: "images/Members/Tharun kumaar.jpg",
    Profile: "Web Dev",
    Year: "B Tech 2nd Year",
    LinkedIn: "",
    Github: "https://github.com/Tharun-b777",
    Website: "",
  },
  {
    id: "22",
    Name: "Paarthiban K",
    Photo: "images/Members/Paarthiban K.jpg",
    Profile: "Web Dev",
    Year: "B Tech 2nd Year",
    LinkedIn: "https://www.linkedin.com/in/paarthiban-k-7409011b7",
    Github: "https://github.com/paarthibank",
    Website: "",
  },
  {
    id: "23",
    Name: "Selva Karthik D",
    Photo: "images/Members/Selva Karthik.jpg",
    Profile: "Web Dev",
    Year: "B Tech 2nd Year",
    LinkedIn: "https://www.linkedin.com/in/selva-karthik-29b994108/",
    Github: "https://github.com/SelvaKarthik17",
    Website: "",
  },
  {
    id: "24",
    Name: "Hetvi Bhansali",
    Photo: "images/Members/Hetvi Bhansali.jpeg",
    Profile: "Web Dev",
    Year: "B Tech 2nd Year",
    LinkedIn: "https://www.linkedin.com/in/hetvibhansali/",
    Github: "https://github.com/hetvi955",
    Website: "",
  },
  {
    id: "25",
    Name: "Sunith Senthil K",
    Photo: "images/Members/Sunith.jpg",
    Profile: "Web Dev",
    Year: "B Tech 2nd Year",
    LinkedIn: "https://www.linkedin.com/in/sunith-senthil-b775581a5",
    Github: "https://github.com/sunith68",
    Website: "",
  },
  {
    id: "26",
    Name: "Deepanshu Dhruw",
    Photo: "images/Members/Deepanshu Dhruw.jpeg",
    Profile: "Web Dev",
    Year: "B Tech 2nd Year",
    LinkedIn: "https://www.linkedin.com/in/devblin",
    Github: "https://github.com/devblin",
    Website: "https://devblin.codes",
  },
  {
    id: "27",
    Name: "Darshana V",
    Photo: "images/Members/Darshana V.jpg",
    Profile: "Web Dev",
    Year: "B Tech 2nd Year",
    LinkedIn: "https://www.linkedin.com/in/darshana-v-075364189/",
    Github: "https://github.com/darshana-v",
    Website: "",
  },
  {
    id: "28",
    Name: "Arnav Menon",
    Photo: "images/Members/Arnav Menon.jpeg",
    Profile: "Web Dev",
    Year: "B Tech 2nd Year",
    LinkedIn: "https://www.linkedin.com/in/arnav-menon-6630a019b/",
    Github: "https://github.com/arnavmenon",
    Website: "",
  },
  {
    id: "29",
    Name: "Sai Sandhya",
    Photo: "images/Members/Sai Sandhya.jpg",
    Profile: "Web Dev",
    Year: "B Tech 2nd Year",
    LinkedIn: "",
    Github: "https://github.com/saisandhya01",
    Website: "",
  },
  {
    id: "30",
    Name: "Mritunjay Kumar",
    Photo: "images/Members/Mritunjay Kumar.jpg",
    Profile: "Algos",
    Year: "MCA 2nd year",
    LinkedIn: "https://www.linkedin.com/in/mritunjay-kumar-a5501b193/",
    Github: "https://github.com/mritunjay583",
    Website: "",
  },
  {
    id: "31",
    Name: "Kundan",
    Photo: "images/Members/Kundan Mandloi.jpg",
    Profile: "Algos",
    Year: "MCA 2nd year",
    LinkedIn: "https://www.linkedin.com/in/kundan-mandloi-078627181/",
    Github: "https://github.com/Kunda31n",
    Website: "",
  },

  {
    id: "32",
    Name: "Harsh Bhadoria",
    Photo: "images/Members/Harsh Bhadoria.jpg",
    Profile: "Algos",
    Year: "MCA 2nd year",
    LinkedIn: "https://www.linkedin.com/in/harsh-bhadoria-989665144/",
    Github: "https://github.com/harshbhadoria011",
    Website: "",
  },
  {
    id: "33",
    Name: "Sri Harsha T.V",
    Photo: "images/Members/Sri Harsha T V.jpeg",
    Profile: "Algos",
    Year: "B Tech 4th year",
    LinkedIn: "https://www.linkedin.com/in/sri-harsha-t-v-b7484a157",
    Github: "https://github.com/tvs1998",
    Website: "",
  },

  {
    id: "35",
    Name: "Dhruv Bodani",
    Photo: "images/Members/Dhruv Bodani.jpg",
    Profile: "Algos",
    Year: "B Tech 4th year",
    LinkedIn: "https://www.linkedin.com/in/dhruv-bodani-254a2b151",
    Github: "https://github.com/dB2510",
    Website: "",
  },
  {
    id: "36",
    Name: "Arvind Tatiparti",
    Photo: "images/Members/Arvind Tatiparti.jpg",
    Profile: "Algos",
    Year: "B Tech 4th year",
    LinkedIn: "https://www.linkedin.com/in/arvindtatiparti/",
    Github: "https://github.com/r0uxt1",
    Website: "",
  },
  {
    id: "37",
    Name: "Aditya Kumar",
    Photo: "images/Members/Aditya Kumar.jpg",
    Profile: "Algos",
    Year: "B Tech 4th year",
    LinkedIn: "https://linkedin.com/in/aditya-kumar-8218ab138",
    Github: "https://github.com/kumaraditya1999",
    Website: "",
  },
  {
    id: "38",
    Name: "Harshit Mogalapalli ",
    Photo: "images/Members/Harshit Mogalapalli.jpg",
    Profile: "Algos",
    Year: "B Tech 4th year",
    LinkedIn: "https://www.linkedin.com/in/harshit-mogalapalli-44025917b",
    Github: "https://github.com/harshimogalapalli",
    Website: "",
  },
  {
    id: "39",
    Name: "Chidanand Dev Suryawanshi",
    Photo: "images/Members/Chidanand Dev Suryawanshi.jpg",
    Profile: "Algos",
    Year: "B Tech 4th year",
    LinkedIn: "https://www.linkedin.com/in/engiiiiinerd",
    Github: "https://github.com/EngiiiiiNERD",
    Website: "",
  },
  {
    id: "40",
    Name: "Soham Roy",
    Photo: "images/Members/Soham Roy.jpg",
    Profile: "Algos",
    Year: "B Tech 4th year",
    LinkedIn: "https://www.linkedin.com/in/sohamroy15",
    Github: "https://www.github.com/wolflegend99",
    Website: "",
  },
  {
    id: "41",
    Name: "Fasith",
    Photo: "images/Members/Fasith Ali.jpeg",
    Profile: "Algos",
    Year: "B Tech 4th year",
    LinkedIn: "https://www.linkedin.com/in/fasith/",
    Github: "https://github.com/Fasith",
    Website: "",
  },
  {
    id: "42",
    Name: "Anoop Kumar",
    Photo: "images/Members/Anoop Kumar.jpg",
    Profile: "Algos",
    Year: "B Tech 4th year",
    LinkedIn: "https://www.linkedin.com/in/anoop-kumar-51284514b/",
    Github: "https://github.com/kumaranoop900",
    Website: "",
  },
  {
    id: "43",
    Name: "Raj Kuvar Yadav",
    Photo: "images/Members/Raj Kuvar.jpg",
    Profile: "Algos",
    Year: "B Tech 4th year",
    LinkedIn: "https://www.linkedin.com/in/raj-kuvar-4ba9b6172",
    Github: "https://github.com/RAJ107",
    Website: "",
  },
  {
    id: "44",
    Name: "Joel Antony Joseph",
    Photo: "images/Members/Joel Antony Joseph.jpg",
    Profile: "Algos",
    Year: "B Tech 4th year",
    LinkedIn: "https://www.linkedin.com/in/joel-antony-joseph-97377315b/",
    Github: "https://github.com/JoAMD",
    Website: "",
  },
  {
    id: "45",
    Name: "Suraj Kumar",
    Photo: "images/Members/Suraj Kumar.jpg",
    Profile: "Algos",
    Year: "B Tech 3rd Year",
    LinkedIn: "https://www.linkedin.com/in/suraj-kumar-700860176",
    Github: "",
    Website: "",
  },
  {
    id: "46",
    Name: "Sankalp Gupta",
    Photo: "images/Members/Sankalp Gupta.jpg",
    Profile: "Algos",
    Year: "B Tech 3rd Year",
    LinkedIn: "https://www.linkedin.com/in/sankalp-gupta-42b84118a",
    Github: "https://github.com/i-am-sank",
    Website: "",
  },

  {
    id: "47",
    Name: "Arvinth Saravanan",
    Photo: "images/Members/Arvinth Saravanan.jpg",
    Profile: "Algos",
    Year: "B Tech 3rd Year",
    LinkedIn: "https://www.linkedin.com/in/arvinth-saravanan-3241b0192/",
    Github: "https://github.com/Arvinth-s",
    Website: "",
  },
  {
    id: "48",
    Name: "Harshit Agrawal",
    Photo: "images/Members/Harshit Agrawal.jpeg",
    Profile: "Algos",
    Year: "B Tech 3rd Year",
    LinkedIn: "https://www.linkedin.com/in/harshit-agrawal-48b74a174/",
    Github: "https://github.com/HarshitCodex",
    Website: "",
  },
  {
    id: "49",
    Name: "Venkataraman V",
    Photo: "images/Members/Venkataraman V.jpeg",
    Profile: "Algos",
    Year: "B Tech 3rd Year",
    LinkedIn: "https://www.linkedin.com/in/venkataraman-v-392090193/",
    Github: "https://github.com/Venkataraman8",
    Website: "",
  },

  {
    id: "52",
    Name: "Anurag Tiwari",
    Photo: "images/Members/Anurag Tiwari.jpeg",
    Profile: "Algos",
    Year: "B Tech 3rd Year",
    LinkedIn: "https://www.linkedin.com/in/anurag-tiwari-25786a176",
    Github: "https://github.com/Anu705",
    Website: "",
  },
  {
    id: "53",
    Name: "Ashish Singh",
    Photo: "images/Members/Ashish Singh.jpg",
    Profile: "Algos",
    Year: "B Tech 3rd Year",
    LinkedIn: "https://www.linkedin.com/in/ashish-singh-19986a176",
    Github: "https://github.com/ashish14012000",
    Website: "",
  },

  {
    id: "54",
    Name: "Nitin Gupta",
    Photo: "images/Members/Nitin Gupta.jpg",
    Profile: "Algos",
    Year: "B Tech 2nd Year",
    LinkedIn: "",
    Github: "https://github.com/nitin0280",
    Website: "",
  },
  {
    id: "55",
    Name: "Ritik Mittal",
    Photo: "images/Members/Ritik Mittal.jpeg",
    Profile: "Algos",
    Year: "B Tech 2nd Year",
    LinkedIn: "https://linkedin.com/in/mittalritik365",
    Github: "https://github.com/ritikmittal",
    Website: "",
  },
  {
    id: "56",
    Name: "Rishab Nahar",
    Photo: "images/Members/Rishab Nahar.jpg",
    Profile: "Algos",
    Year: "B Tech 2nd Year",
    LinkedIn: "",
    Github: "https://github.com/rishab-nahar",
    Website: "",
  },
  {
    id: "57",
    Name: "Satyarth Pandey",
    Photo: "images/Members/Satyarth Pandey.jpg",
    Profile: "Algos",
    Year: "B Tech 2nd Year",
    LinkedIn: "https://www.linkedin.com/in/satyarth-pandey-42a6021a4",
    Github: "https://github.com/satyarth413",
    Website: "",
  },
  {
    id: "58",
    Name: "Sobhagya Singh Dewal",
    Photo: "images/Members/Sobhagya Singh Dewal.jpg",
    Profile: "Algos",
    Year: "B Tech 2nd Year",
    LinkedIn: "",
    Github: "",
    Website: "",
  },
  {
    id: "59",
    Name: "Rhithick Murali",
    Photo: "images/Members/Rhithick .M.jpg",
    Profile: "Algos",
    Year: "B Tech 2nd Year",
    LinkedIn: "https://www.linkedin.com/in/rhithick-murali-634154191",
    Github: "https://github.com/Rhithick02",
    Website: "",
  },

  {
    id: "60",
    Name: "Priyanka Singh",
    Photo: "images/Members/Priyanka Singh.jpg",
    Profile: "Algos",
    Year: "B Tech 2nd Year",
    LinkedIn: "https://www.linkedin.com/in/priyanka-singh-8598761a1/",
    Github: "https://github.com/priyandroid",
    Website: "",
  },
  {
    id: "61",
    Name: "Shivam Pradhan",
    Photo: "images/Members/Shivam Pradhan.jpeg",
    Profile: "Algos",
    Year: "B Tech 2nd Year",
    LinkedIn: "",
    Github: "https://github.com/Shivam1309",
    Website: "",
  },

  {
    id: "62",
    Name: "Preksha Rakhecha",
    Photo: "images/Members/Preksha Rakhecha.JPG",
    Profile: "Algos",
    Year: "B Tech 2nd Year",
    LinkedIn: "https://www.linkedin.com/in/preksha-rakhecha-5b273819b/",
    Github: "https://github.com/preksha121",
    Website: "",
  },
  {
    id: "63",
    Name: "Parvathi Prabhakaran",
    Photo: "images/Members/Parvathi KP.jpg",
    Profile: "Algos",
    Year: "B Tech 2nd Year",
    LinkedIn: "https://www.linkedin.com/in/parvathi-prabhakaran-799744194",
    Github: "https://github.com/parvathikp",
    Website: "",
  },
  {
    id: "64",
    Name: "Manav Mohata",
    Photo: "images/Members/Manav Mohata.jpg",
    Profile: "Algos",
    Year: "B Tech 2nd Year",
    LinkedIn: "https://www.linkedin.com/in/manav-mohata-2ba778190/",
    Github: "https://github.com/manav-06",
    Website: "",
  },
  {
    id: "65",
    Name: "Jack Samuel",
    Photo: "images/new-core/jack.jpg",
    Profile: "Tronix",
    Year: "B Tech 4th year",
    LinkedIn: "https://www.linkedin.com/in/jacksamuel98/",
    Github: "",
    Website: "",
  },

  {
    id: "66",
    Name: "Mukesh Gandhi",
    Photo: "images/Members/Mukesh Gandhi.jpg",
    Profile: "Tronix",
    Year: "B Tech 4th year",
    LinkedIn: "https://www.linkedin.com/in/mukesh-gandhi-8b7939128",
    Github: "https://github.com/MukkeshGandhi09",
    Website: "",
  },
  {
    id: "67",
    Name: "Aditya R",
    Photo: "images/Members/Aditya Ravi.jpg",
    Profile: "Tronix",
    Year: "B Tech 4th year",
    LinkedIn: "https://www.linkedin.com/in/aditya-ravichander-b2584b178",
    Github: "https://github.com/adityaravichander",
    Website: "",
  },
  {
    id: "68",
    Name: "Akil M",
    Photo: "images/Members/Akil M.jpg",
    Profile: "Tronix",
    Year: "B Tech 4th year",
    LinkedIn: "https://www.linkedin.com/in/akil-m/",
    Github: "https://github.com/akilm",
    Website: "",
  },
  {
    id: "69",
    Name: "Aditya Kumar Singh",
    Photo: "images/Members/Aditya Singh.jpg",
    Profile: "Tronix",
    Year: "B Tech 4th year",
    LinkedIn: "https://www.linkedin.com/in/aditya-kumar-singh-645996152/",
    Github: "https://github.com/adityasingh3007",
    Website: "https://adityasingh3007.github.io/",
  },

  {
    id: "70",
    Name: "Kathirvel Rajan B",
    Photo: "images/Members/CBK - kathirvel rajan.jpeg",
    Profile: "Tronix",
    Year: "B Tech 4th year",
    LinkedIn: "https://www.linkedin.com/in/kathirvelrajan22112002/",
    Github: "https://github.com/cbkathir",
    Website: "",
  },
  {
    id: "71",
    Name: "Ruphan S",
    Photo: "images/Members/Ruphan S.jpg",
    Profile: "Tronix",
    Year: "B Tech 4th year",
    LinkedIn: "https://www.linkedin.com/in/ruphan-s-37412673",
    Github: "https://github.com/ruphan",
    Website: "",
  },

  {
    id: "72",
    Name: "Manu Aatitya R P",
    Photo: "images/Members/Manu Aatitya.jpg",
    Profile: "Tronix",
    Year: "B Tech 4th year",
    LinkedIn: "https://www.linkedin.com/in/manu-aatitya-r-p-78457412b/",
    Github: "https://github.com/manuaatitya",
    Website: "",
  },
  {
    id: "73",
    Name: "Sudharsan S",
    Photo: "images/Members/Sudharsan Sundararaj.jpeg",
    Profile: "Tronix",
    Year: "B Tech 3rd Year",
    LinkedIn: "https://www.linkedin.com/in/sudharsan-s-1a7a1317b/",
    Github: "https://github.com/sudharsan2000",
    Website: "",
  },
  {
    id: "74",
    Name: "S P Sharan",
    Photo: "images/Members/Sharan SP.jpg",
    Profile: "Tronix",
    Year: "B Tech 3rd Year",
    LinkedIn: "https://www.linkedin.com/in/sharan-sp-05735a168",
    Github: "https://github.com/Syzygianinfern0",
    Website: "",
  },
  {
    id: "75",
    Name: "Anbuselvan D",
    Photo: "images/Members/Anbu Selvan.jpeg",
    Profile: "Tronix",
    Year: "B Tech 3rd Year",
    LinkedIn: "https://ca.linkedin.com/in/anbu52",
    Github: "https://github.com/anbu52",
    Website: "",
  },
  {
    id: "76",
    Name: "Kumar Gaurav Singh",
    Photo: "images/Members/Gaurav Singh.jpg",
    Profile: "Tronix",
    Year: "B Tech 3rd Year",
    LinkedIn: "https://www.linkedin.com/in/gaurav-singh-0b056117b",
    Github: "https://github.com/GauravSingh789",
    Website: "",
  },
  {
    id: "77",
    Name: "Kirthika Srinivasan ",
    Photo: "images/Members/Kirthika Srinivasan.jpg",
    Profile: "Tronix",
    Year: "B Tech 3rd Year",
    LinkedIn: "https://www.linkedin.com/in/kirthika-srinivasan-6a9614181",
    Github: "https://github.com/kirthi-ka",
    Website: "",
  },
  {
    id: "78",
    Name: "Anagha Sethuraman",
    Photo: "images/Members/Anagha Sethuraman.jpg",
    Profile: "Tronix",
    Year: "B Tech 3rd Year",
    LinkedIn: "https://www.linkedin.com/in/anagha-sethuraman-192148179/",
    Github: "https://github.com/AnaghaSethuraman",
    Website: "",
  },
  {
    id: "79",
    Name: "Akshaya Subramanian",
    Photo: "images/Members/Akshaya Subramanian.jpeg",
    Profile: "Tronix",
    Year: "B Tech 3rd Year",
    LinkedIn: "https://www.linkedin.com/in/akshaya-subramanian-a6a609185/",
    Github: "https://github.com/AkshayaCSubramanian",
    Website: "",
  },
  {
    id: "80",
    Name: "Miriam Santhosh Kadavan",
    Photo: "images/Members/Miriam.jpg",
    Profile: "Tronix",
    Year: "B Tech 3rd Year",
    LinkedIn: "https://www.linkedin.com/in/miriam-santhosh-kadavan-30927a193/",
    Github: "https://github.com/Githubmsk",
    Website: "",
  },

  {
    id: "81",
    Name: "Himanshu Nandan",
    Photo: "images/Members/Himanshu Nandan.jpg",
    Profile: "Tronix",
    Year: "B Tech 2nd Year",
    LinkedIn: "https://www.linkedin.com/in/himanshu-nandan-4b628a18a",
    Github: "https://github.com/himanshunandan292",
    Website: "",
  },
  {
    id: "82",
    Name: "Manu S",
    Photo: "images/Members/Manu Sekar.jpeg",
    Profile: "Tronix",
    Year: "B Tech 2nd Year",
    LinkedIn: "https://www.linkedin.com/in/manu-sekar-9824351b7/",
    Github: "https://github.com/Manu-Sekar",
    Website: "",
  },
  {
    id: "83",
    Name: "P M Venkata Nagarjun",
    Photo: "images/Members/Venkata Nagarjun P M.jpeg",
    Profile: "Tronix",
    Year: "B Tech 2nd Year",
    LinkedIn: "https://www.linkedin.com/in/venkata-nagarjun-p-m-57190b19a/",
    Github: "https://github.com/Arjun191",
    Website: "",
  },
  {
    id: "84",
    Name: "Ishikaa Lunawat",
    Photo: "images/Members/Ishikaa Lunawat.jpg",
    Profile: "Tronix",
    Year: "B Tech 2nd Year",
    LinkedIn: "https://www.linkedin.com/in/ishikaa-lunawat-776241193",
    Github: "https://github.com/ishikaa25",
    Website: "",
  },
  {
    id: "85",
    Name: "V Prakash",
    Photo: "images/Members/V Prakash.jpeg",
    Profile: "Tronix",
    Year: "B Tech 2nd Year",
    LinkedIn: "",
    Github: "https://github.com/prakash2708",
    Website: "",
  },
  {
    id: "86",
    Name: "Shankar Utthandy V",
    Photo: "images/Members/Shankar Utthandy V.jpg",
    Profile: "Tronix",
    Year: "B Tech 2nd Year",
    LinkedIn: "",
    Github: "",
    Website: "",
  },
  {
    id: "87",
    Name: "G Arvindaksha",
    Photo: "images/Members/Arvindaksha G.jpg",
    Profile: "Tronix",
    Year: "B Tech 2nd Year",
    LinkedIn: "https://www.linkedin.com/in/arvindaksha-g-15622a1a8/",
    Github: "https://github.com/Arvindaksha",
    Website: "",
  },
  {
    id: "88",
    Name: "Arunesh Saddish",
    Photo: "images/Members/Arunesh Saddish.jpeg",
    Profile: "Tronix",
    Year: "B Tech 2nd Year",
    LinkedIn: "https://www.linkedin.com/in/arunesh-saddish-26747519a/",
    Github: "https://github.com/arunesh006",
    Website: "",
  },
  {
    id: "89",
    Name: "Visweswaran B",
    Photo: "images/Members/B Visweswaran.jpg",
    Profile: "Tronix",
    Year: "B Tech 2nd Year",
    LinkedIn: "https://www.linkedin.com/in/visweswaran-b-1675271b4",
    Github: "https://github.com/Vichu-31101",
    Website: "",
  },
  {
    id: "90",
    Name: "Sree Ganesh TN",
    Photo: "images/Members/Sree Ganesh.jpg",
    Profile: "Tronix",
    Year: "B Tech 2nd Year",
    LinkedIn: "",
    Github: "https://github.com/SreeGaneshTN",
    Website: "",
  },
  {
    id: "91",
    Name: "Varshini Priyaa",
    Photo: "images/Members/Varshini Priyaa.jpeg",
    Profile: "Tronix",
    Year: "B Tech 2nd Year",
    LinkedIn:
      "https://www.linkedin.com/in/varshini-priyaa-senthilnathan-83661314a/",
    Github: "https://github.com/varshinisn",
    Website: "",
  },
  {
    id: "92",
    Name: "Vignesh S",
    Photo: "images/Members/Vignesh S.jpeg",
    Profile: "Tronix",
    Year: "B Tech 2nd Year",
    LinkedIn: "`https://www.linkedin.com/in/vignesh-s-3754311b7/",
    Github: "https://github.com/VickyRDK",
    Website: "",
  },
  {
    id: "93",
    Name: "Vivek Malviya",
    Photo: "images/Members/Vivek Malviya.jpg",
    Profile: "Tronix",
    Year: "B Tech 2nd Year",
    LinkedIn: "https://www.linkedin.com/in/vivek-malviya-a10b141b6/",
    Github: "https://github.com/VivekMal29",
    Website: "",
  },
  {
    id: "94",
    Name: "A.Shanmuga Sundaram",
    Photo: "images/Members/Shanmuga Sundaram.jpg",
    Profile: "Tronix",
    Year: "B Tech 2nd Year",
    LinkedIn:
      "https://www.linkedin.com/in/shanmuga-sundaram-5983271b3?lipi=urn%3Ali%3Apage%3Ad_flagship3_profile_view_base_contact_details%3BYrts7jF1SXqUkntP2v4VhA%3D%3D",
    Github: "https://github.com/shan2501",
    Website: "",
  },
  {
    id: "95",
    Name: "N Srikrishna",
    Photo: "images/Members/SrikrishnaN.jpg",
    Profile: "Tronix",
    Year: "B Tech 2nd Year",
    LinkedIn: "https://www.linkedin.com/in/srikrishna-neelakantan-5751b7120",
    Github: "https://github.com/2001srikrishna",
    Website: "",
  },
  {
    id: "96",
    Name: "Surya Thanush",
    Photo: "images/Members/Surya Thanush.jpeg",
    Profile: "Tronix",
    Year: "B Tech 2nd Year",
    LinkedIn: "",
    Github: "https://github.com/suryathanush",
    Website: "",
  },
  {
    id: "97",
    Name: "Himanshu Nandan",
    Photo: "images/Members/Himanshu Nandan.jpg",
    Profile: "Tronix",
    Year: "B Tech 2nd Year",
    LinkedIn: "https://www.linkedin.com/in/himanshu-nandan-4b628a18a",
    Github: "https://github.com/himanshunandan292",
    Website: "",
  },
  {
    id: "98",
    Name: "Arijit Biswas",
    Photo: "images/Members/Arijit Biswas.jpg",
    Profile: "App Dev",
    Year: "MCA 2nd year",
    LinkedIn: "https://www.linkedin.com/in/arijit-biswas-b7a85a98",
    Github: "https://github.com/arijitbiswasraj/",
    Website: "",
  },
  {
    id: "99",
    Name: "Disha Raj",
    Photo: "images/Members/Disha Raj.jpeg",
    Profile: "App Dev",
    Year: "MCA 2nd year",
    LinkedIn: "https://www.linkedin.com/in/disha-raj-284a05116",
    Github: "https://github.com/DishaRaj",
    Website: "",
  },
  {
    id: "100",
    Name: "Shivam Tiwari",
    Photo: "images/Members/Shivam Tiwari.jpg",
    Profile: "App Dev",
    Year: "MCA 2nd year",
    LinkedIn: "https://www.linkedin.com/in/shivam-tiwari-32018b175",
    Github: "https://github.com/shivamtiwari841797",
    Website: "",
  },
  {
    id: "101",
    Name: "Vaibhav Bairagi",
    Photo: "images/Members/Vaibhav Bairagi.jpg",
    Profile: "App Dev",
    Year: "B Tech 3rd Year",
    LinkedIn: "https://www.linkedin.com/in/vaibhav-bairagi-a6ab97161",
    Github: "https://github.com/Vaibhavbairagi",
    Website: "",
  },
  {
    id: "102",
    Name: "Amogh J",
    Photo: "images/Members/Amogh Jahagirdar.jpg",
    Profile: "App Dev",
    Year: "B Tech 4th year",
    LinkedIn: "https://www.linkedin.com/in/amoghjahagirdar/",
    Github: "https://github.com/amogh-jrules",
    Website: "https://amogh-jrules.github.io",
  },
  {
    id: "103",
    Name: "Nitin More",
    Photo: "images/Members/Nitin More.jpg",
    Profile: "App Dev",
    Year: "B Tech 4th year",
    LinkedIn: "https://www.linkedin.com/in/nitin-more/",
    Github: "https://github.com/NitinMore7",
    Website: "",
  },
  {
    id: "104",
    Name: "Ark Srivastava",
    Photo: "images/Members/Ark  Srivatsvava.jpg",
    Profile: "App Dev",
    Year: "B Tech 4th year",
    LinkedIn: "https://www.linkedin.com/in/ark-srivastava-252542160",
    Github: "https://github.com/rarsahki",
    Website: "",
  },
  {
    id: "105",
    Name: "Goutham C M",
    Photo: "images/Members/Goutham CM.jpeg",
    Profile: "App Dev",
    Year: "B Tech 4th year",
    LinkedIn: "https://www.linkedin.com/in/goutham-c-m-5a0621154/",
    Github: "https://github.com/gouthamcm",
    Website: "",
  },
  {
    id: "106",
    Name: "Ayush Singh",
    Photo: "images/Members/Ayush Singh.jpg",
    Profile: "App Dev",
    Year: "B Tech 3rd Year",
    LinkedIn: "https://www.linkedin.com/in/ayushsinghs/",
    Github: "https://github.com/ayush547",
    Website: "",
  },
  {
    id: "107",
    Name: "Naren Sairam",
    Photo: "images/Members/Naren Sairam.jpg",
    Profile: "App Dev",
    Year: "B Tech 3rd Year",
    LinkedIn: "https://www.linkedin.com/in/naren-sairam-941739173",
    Github: "https://github.com/nsi319",
    Website: "",
  },
  {
    id: "108",
    Name: "Madhav Aggarwal",
    Photo: "images/Members/Madhav Aggarwal.jpg",
    Profile: "App Dev",
    Year: "B Tech 3rd Year",
    LinkedIn: "https://www.linkedin.com/in/madhav-aggarwal-b16180181/",
    Github: "https://github.com/madhavaggar",
    Website: "",
  },
  {
    id: "109",
    Name: "Harshit Singh",
    Photo: "images/Members/Harshit Singh.jpg",
    Profile: "App Dev",
    Year: "B Tech 3rd Year",
    LinkedIn: "https://www.linkedin.com/in/harshit-singh-83110a193/",
    Github: "https://github.com/LightHarshit",
    Website: "",
  },
  {
    id: "110",
    Name: "Khushali Patel",
    Photo: "images/Members/Khushali Patel.jpg",
    Profile: "App Dev",
    Year: "B Tech 3rd Year",
    LinkedIn: "https://www.linkedin.com/in/khushali-patel-92b182179",
    Github: "https://github.com/khushali259",
    Website: "",
  },
  {
    id: "111",
    Name: "Isha Waghulde",
    Photo: "images/Members/Isha Waghulde.jpg",
    Profile: "App Dev",
    Year: "B Tech 3rd Year",
    LinkedIn: "https://www.linkedin.com/in/isha-waghulde-4529aa17b",
    Github: "https://github.com/ishawaghulde.",
    Website: "",
  },
  {
    id: "112",
    Name: "S P Srinidhi",
    Photo: "images/Members/Srinidhi.jpg",
    Profile: "App Dev",
    Year: "B Tech 3rd Year",
    LinkedIn: "http://www.linkedin.com/in/srinidhi-s-p-b005b4171",
    Github: "https://github.com/Srinidhi2000",
    Website: "",
  },

  {
    id: "113",
    Name: "Abhinav Kothari",
    Photo: "images/Members/Abhinav Kothari.jpg",
    Profile: "App Dev",
    Year: "B Tech 2nd Year",
    LinkedIn: "https://www.linkedin.com/in/abhinav-kothari-67045b199",
    Github: "https://github.com/AK-Zero",
    Website: "",
  },
  {
    id: "114",
    Name: "Gokul P",
    Photo: "images/Members/Gokul Palaniappan.jpg",
    Profile: "App Dev",
    Year: "B Tech 2nd Year",
    LinkedIn: "https://www.linkedin.com/in/gokul-p-2b174a197/",
    Github: "https://github.com/Gokul-31",
    Website: "",
  },
  {
    id: "115",
    Name: "Haemanth V",
    Photo: "images/Members/Haemanth V.jpg",
    Profile: "App Dev",
    Year: "B Tech 2nd Year",
    LinkedIn: "https://www.linkedin.com/in/haemanth-v-951176191",
    Github: "https://github.com/Haemanth-V",
    Website: "",
  },
  {
    id: "116",
    Name: "Anand Pandey",
    Photo: "images/Members/Anand Pandey.jpeg",
    Profile: "App Dev",
    Year: "B Tech 2nd Year",
    LinkedIn: "https://www.linkedin.com/in/anand-pandey6599/",
    Github: "https://github.com/Anand-oops",
    Website: "https://www.instagram.com/anand.pandey__/?hl=en",
  },
  {
    id: "117",
    Name: "Vaasu Gambhir",
    Photo: "images/Members/Vaasu Gambhir.jpg",
    Profile: "App Dev",
    Year: "B Tech 2nd Year",
    LinkedIn: "https://www.linkedin.com/in/vaasu-gambhir-5939b5191/",
    Github: "https://github.com/Vaasuawesome7",
    Website: "",
  },
  {
    id: "118",
    Name: "Dharun Vaibhav U",
    Photo: "images/Members/Dharun Vaibhav U.jpeg",
    Profile: "App Dev",
    Year: "B Tech 2nd Year",
    LinkedIn: "https://www.linkedin.com/in/dharun-vaibhav-u-081b001a1/",
    Github: "https://github.com/Dharun1704",
    Website: "",
  },
  {
    id: "119",
    Name: "Sanjeev Vijayakumar",
    Photo: "images/Members/Sanjeev Vijayakumar.jpg",
    Profile: "App Dev",
    Year: "B Tech 2nd Year",
    LinkedIn: "https://www.linkedin.com/in/sanjeev-vijayakumar-060801/",
    Github: "https://github.com/sanjeevmax6/",
    Website: "",
  },
  {
    id: "120",
    Name: "Ankur Sinha",
    Photo: "images/Members/Ankur Sinha.jpg",
    Profile: "App Dev",
    Year: "B Tech 2nd Year",
    LinkedIn: "https://www.linkedin.com/in/ankur-sinha-811653188",
    Github: "https://github.com/ankursinha03",
    Website: "",
  },

  {
    id: "121",
    Name: "R.Harshavardhan",
    Photo: "images/Members/Harshavardhan Ravichandran.jpg",
    Profile: "App Dev",
    Year: "B Tech 2nd Year",
    LinkedIn: "https://www.linkedin.com/in/harshavardhan-r-85393310a",
    Github: "https://github.com/HR-5",
    Website: "",
  },
  // Exception
  {
    id: "122",
    Name: "Rishabh Taparia",
    Photo: "images/Members/Rishabh Taparia.jpg",
    Profile: "Web Dev",
    Year: "B Tech 2nd Year",
    LinkedIn: "https://www.linkedin.com/in/rishabh-t-837751b8",
    Github: "https://github.com/rt1301",
    Website: "",
  },
  {
    id: "123",
    Name: "Aryan Wadhavekar",
    Photo: "images/Members/Aryan Wadhavekar.jpg",
    Profile: "App Dev",
    Year: "B Tech 2nd Year",
    LinkedIn: "https://www.linkedin.com/in/aryan-wadhavekar-9ab63b1b2",
    Github: "https://github.com/aryanmw",
    Website: "",
  },
  {
    id: "124",
    Name: "Arihant Banthia",
    Photo: "images/Members/Arihant.jpg",
    Profile: "Web Dev",
    Year: "MCA 2nd year",
    Linkedin: "https://www.linkedin.com/in/arihant-banthia-834343130/",
    Github: "https://github.com/sachajoy",
  },
  {
    id: "125",
    Name: "Adithya K Krishna",
    Photo: "images/Members/Adithya K Krishna.jpg",
    Profile: "Tronix",
    Year: "B Tech 3rd Year",
    LinkedIn: "https://www.linkedin.com/in/adithya-k-krishna-3a6087193/",
    Github: "https://github.com/AdithyaK243",
    Website: "",
  },
  {
    id: "126",
    Name: "Siddharth Rao A",
    Photo: "images/Members/Siddharth Rao A.jpg",
    Profile: "Tronix",
    Year: "B Tech 3rd Year",
    LinkedIn: "https: //www.linkedin.com/in/siddharth-rao-a-b3b140198",
    Github: "https://github.com/SiddharthRaoA",
    Website: "",
  },
  {
    id: "127",
    Name: "Premkumar N",
    Photo: "images/Members/Premkumar.jpg",
    Profile: "Tronix",
    Year: "B Tech 2nd Year",
    LinkedIn: "https://www.linkedin.com/in/prem-kumar-6ba457136/",
    Github: "https://github.com/pk1510/",
    Website: "",
  },
  // ---------------------------------------------------------------------------------------------------------
  // ------------------------------------------------ ALL ----------------------------------------------------
  // ---------------------------------------------------------------------------------------------------------
  {
    id: "1",
    Name: "Kishore",
    Photo: "images/Members/Kishore V.jpg",
    Profile: "Web Dev",
    Year: "All",
    LinkedIn: "https://www.linkedin.com/in/kishore-v-a006ab153/",
    Github: "https://github.com/Kishorehere",
    Website: "",
  },
  {
    id: "2",
    Name: "S Raghul",
    Photo: "images/Members/Raghul Sivavenkatesh.jpg",
    Profile: "Web Dev",
    Year: "All",
    LinkedIn: "https://www.linkedin.com/in/sraghul127",
    Github: "https://github.com/Raghul127",
    Website: "https://raghul127.github.io/",
  },
  {
    id: "3",
    Name: "P Naveena",
    Photo: "images/Members/Naveena.jpg",
    Profile: "Web Dev",
    Year: "All",
    LinkedIn: "https://www.linkedin.com/in/na899",
    Github: "https://github.com/na899",
    Website: "",
  },
  {
    id: "4",
    Name: "Vishal Saranathan",
    Photo: "images/Members/Vishal Saranathan.jpg",
    Profile: "Web Dev",
    Year: "All",
    LinkedIn: "https://www.linkedin.com/in/vishal-s-126000145/",
    Github: "https://github.com/VishalS99",
    Website: "",
  },

  {
    id: "5",
    Name: "Mohamed Sohail",
    Photo: "images/Members/Mohammed Sohail.jpg",
    Profile: "Web Dev",
    Year: "All",
    LinkedIn: "https://www.linkedin.com/in/mohamedsohail/",
    Github: "https://github.com/kamikazechaser",
    Website: "https:kamikazechaser.github.io",
  },
  {
    id: "6",
    Name: "Prakhar Singh",
    Photo: "images/Members/Prakhar Singh.jpg",
    Profile: "Web Dev",
    Year: "All",
    LinkedIn: "https://www.linkedin.com/in/prakhar-singh-852110173/",
    Github: "https://github.com/prakhar242",
    Website: "",
  },
  {
    id: "7",
    Name: "N Praveen Chandhar",
    Photo: "images/Members/N Praveen Chandhar.jpg",
    Profile: "Web Dev",
    Year: "All",
    LinkedIn: "https://www.linkedin.com/in/praveen27/",
    Github: "https://github.com/gigatesseract/",
    Website: "https://gigatesseract.github.io/",
  },
  {
    id: "8",
    Name: "Joel Johnson",
    Photo: "images/Members/Joel Johnson.jpeg",
    Profile: "Web Dev",
    Year: "All",
    LinkedIn: "https://www.linkedin.com/in/joel-johnson-36694015b/",
    Github: "https://github.com/quantum-jo",
    Website: "joeljohnson.me",
  },
  {
    id: "9",
    Name: "Kamalesh Palanisamy",
    Photo: "images/Members/Kamalesh Palanisamy.jpg",
    Profile: "Web Dev",
    Year: "All",
    LinkedIn: "https://www.linkedin.com/in/kamalesh-palanisamy-2b5265149/",
    Github: "https://github.com/kamalesh0406",
    Website: "http://www.kamaleshp.com",
  },

  {
    id: "10",
    Name: "Anish C ",
    Photo: "images/Members/Chakkirala Anish.jpg",
    Profile: "Web Dev",
    Year: "All",
    LinkedIn: "https://donothaveone.com",
    Github: "https://github.com/chakki1234",
    Website: "",
  },
  {
    id: "11",
    Name: "Anjaneya Tripathi",
    Photo: "images/Members/Anjaneya Tripathi.jpeg",
    Profile: "Web Dev",
    Year: "All",
    LinkedIn: "https://www.linkedin.com/in/anjaneya-tripathi-610234183/",
    Github: "https://github.com/AnjaneyaTripathi",
    Website: "",
  },
  {
    id: "12",
    Name: "Thrishik Senthilkumar",
    Photo: "images/Members/Thrishik Senthilkumar.jpg",
    Profile: "Web Dev",
    Year: "All",
    LinkedIn: "https://in.linkedin.com/in/thrishik-senthilkumar-123918176",
    Github: "https://github.com/thrishik7",
    Website: "",
  },
  {
    id: "13",
    Name: "Barath Kumar S",
    Photo: "images/Members/Barath.png",
    Profile: "Web Dev",
    Year: "All",
    LinkedIn: "https://linkedin.com/in/barath1999",
    Github: "https://www.github.com/barath99",
    Website: "https://barath99.github.io",
  },
  {
    id: "14",
    Name: "Smrithi Prakash",
    Photo: "images/Members/Smrithi.png",
    Profile: "Web Dev",
    Year: "All",
    LinkedIn: "https://linkedin.com/in/smrithi-prakash-452173193",
    Github: "https://github.com/Smrithi23",
    Website: "",
  },
  {
    id: "15",
    Name: "Jerry J",
    Photo: "images/Members/Jerry.png",
    Profile: "Web Dev",
    Year: "All",
    LinkedIn: "https://www.linkedin.com/in/jerry-j-89aa52174/",
    Github: "https://github.com/Hank-learner",
    Website: "",
  },
  {
    id: "16",
    Name: "Amar Rokade",
    Photo: "images/Members/Amar Rokade.jpg",
    Profile: "Web Dev",
    Year: "All",
    LinkedIn: "https://www.linkedin.com/in/amar-rokade-903a82184/",
    Github: "https://github.com/amar-rokade",
    Website: "",
  },
  {
    id: "17",
    Name: "Gokulraaj",
    Photo: "images/Members/Gokulraaj Vaithiyanathan.jpg",
    Profile: "Web Dev",
    Year: "All",
    LinkedIn: "https://www.linkedin.com/in/gokulraaj-vaithiyanathan-a7b7781a5",
    Github: "https://github.com/gokul-00",
    Website: "https://im-gokul.netlify.app/",
  },
  {
    id: "18",
    Name: "Subramanian V V",
    Photo: "images/Members/Subramanian.jpg",
    Profile: "Web Dev",
    Year: "All",
    LinkedIn: "https://www.linkedin.com/in/subramanian-v-v-85563a1a6",
    Github: "https://github.com/subramanian-vv",
    Website: "",
  },
  {
    id: "19",
    Name: "Mansi Bisen",
    Photo: "images/Members/Mansi Bisen.jpeg",
    Profile: "Web Dev",
    Year: "All",
    LinkedIn: "https://www.linkedin.com/in/mansi-bisen-23a26118b",
    Github: "https://github.com/Mansibisen",
    Website: "",
  },
  {
    id: "20",
    Name: "Mohana Sundaram S",
    Photo: "images/Members/Mohana Sundaram.jpeg",
    Profile: "Web Dev",
    Year: "All",
    LinkedIn: "https://www.linkedin.com/in/mohana-sundaram-s-90a458190/",
    Github: "https://github.com/highonweb",
    Website: "https://msundaram.me",
  },

  {
    id: "21",
    Name: "Tharun Kumaar",
    Photo: "images/Members/Tharun kumaar.jpg",
    Profile: "Web Dev",
    Year: "All",
    LinkedIn: "",
    Github: "https://github.com/Tharun-b777",
    Website: "",
  },
  {
    id: "22",
    Name: "Paarthiban K",
    Photo: "images/Members/Paarthiban K.jpg",
    Profile: "Web Dev",
    Year: "All",
    LinkedIn: "https://www.linkedin.com/in/paarthiban-k-7409011b7",
    Github: "https://github.com/paarthibank",
    Website: "",
  },
  {
    id: "23",
    Name: "Selva Karthik D",
    Photo: "images/Members/Selva Karthik.jpg",
    Profile: "Web Dev",
    Year: "All",
    LinkedIn: "https://www.linkedin.com/in/selva-karthik-29b994108/",
    Github: "https://github.com/SelvaKarthik17",
    Website: "",
  },
  {
    id: "24",
    Name: "Hetvi Bhansali",
    Photo: "images/Members/Hetvi Bhansali.jpeg",
    Profile: "Web Dev",
    Year: "All",
    LinkedIn: "https://www.linkedin.com/in/hetvibhansali/",
    Github: "https://github.com/hetvi955",
    Website: "",
  },
  {
    id: "25",
    Name: "Sunith Senthil K",
    Photo: "images/Members/Sunith.jpg",
    Profile: "Web Dev",
    Year: "All",
    LinkedIn: "https://www.linkedin.com/in/sunith-senthil-b775581a5",
    Github: "https://github.com/sunith68",
    Website: "",
  },
  {
    id: "26",
    Name: "Deepanshu Dhruw",
    Photo: "images/Members/Deepanshu Dhruw.jpeg",
    Profile: "Web Dev",
    Year: "All",
    LinkedIn: "https://www.linkedin.com/in/devblin",
    Github: "https://github.com/devblin",
    Website: "https://devblin.codes",
  },
  {
    id: "27",
    Name: "Darshana V",
    Photo: "images/Members/Darshana V.jpg",
    Profile: "Web Dev",
    Year: "All",
    LinkedIn: "https://www.linkedin.com/in/darshana-v-075364189/",
    Github: "https://github.com/darshana-v",
    Website: "",
  },
  {
    id: "28",
    Name: "Arnav Menon",
    Photo: "images/Members/Arnav Menon.jpeg",
    Profile: "Web Dev",
    Year: "All",
    LinkedIn: "https://www.linkedin.com/in/arnav-menon-6630a019b/",
    Github: "https://github.com/arnavmenon",
    Website: "",
  },
  {
    id: "29",
    Name: "Sai Sandhya",
    Photo: "images/Members/Sai Sandhya.jpg",
    Profile: "Web Dev",
    Year: "All",
    LinkedIn: "",
    Github: "https://github.com/saisandhya01",
    Website: "",
  },
  {
    id: "30",
    Name: "Mritunjay Kumar",
    Photo: "images/Members/Mritunjay Kumar.jpg",
    Profile: "Algos",
    Year: "All",
    LinkedIn: "https://www.linkedin.com/in/mritunjay-kumar-a5501b193/",
    Github: "https://github.com/mritunjay583",
    Website: "",
  },
  {
    id: "31",
    Name: "Kundan",
    Photo: "images/Members/Kundan Mandloi.jpg",
    Profile: "Algos",
    Year: "All",
    LinkedIn: "https://www.linkedin.com/in/kundan-mandloi-078627181/",
    Github: "https://github.com/Kunda31n",
    Website: "",
  },

  {
    id: "32",
    Name: "Harsh Bhadoria",
    Photo: "images/Members/Harsh Bhadoria.jpg",
    Profile: "Algos",
    Year: "All",
    LinkedIn: "https://www.linkedin.com/in/harsh-bhadoria-989665144/",
    Github: "https://github.com/harshbhadoria011",
    Website: "",
  },
  {
    id: "33",
    Name: "Sri Harsha T.V",
    Photo: "images/Members/Sri Harsha T V.jpeg",
    Profile: "Algos",
    Year: "All",
    LinkedIn: "https://www.linkedin.com/in/sri-harsha-t-v-b7484a157",
    Github: "https://github.com/tvs1998",
    Website: "",
  },

  {
    id: "35",
    Name: "Dhruv Bodani",
    Photo: "images/Members/Dhruv Bodani.jpg",
    Profile: "Algos",
    Year: "All",
    LinkedIn: "https://www.linkedin.com/in/dhruv-bodani-254a2b151",
    Github: "https://github.com/dB2510",
    Website: "",
  },
  {
    id: "36",
    Name: "Arvind Tatiparti",
    Photo: "images/Members/Arvind Tatiparti.jpg",
    Profile: "Algos",
    Year: "All",
    LinkedIn: "https://www.linkedin.com/in/arvindtatiparti/",
    Github: "https://github.com/r0uxt1",
    Website: "",
  },
  {
    id: "37",
    Name: "Aditya Kumar",
    Photo: "images/Members/Aditya Kumar.jpg",
    Profile: "Algos",
    Year: "All",
    LinkedIn: "https://linkedin.com/in/aditya-kumar-8218ab138",
    Github: "https://github.com/kumaraditya1999",
    Website: "",
  },
  {
    id: "38",
    Name: "Harshit Mogalapalli ",
    Photo: "images/Members/Harshit Mogalapalli.jpg",
    Profile: "Algos",
    Year: "All",
    LinkedIn: "https://www.linkedin.com/in/harshit-mogalapalli-44025917b",
    Github: "https://github.com/harshimogalapalli",
    Website: "",
  },
  {
    id: "39",
    Name: "Chidanand Dev Suryawanshi",
    Photo: "images/Members/Chidanand Dev Suryawanshi.jpg",
    Profile: "Algos",
    Year: "All",
    LinkedIn: "https://www.linkedin.com/in/engiiiiinerd",
    Github: "https://github.com/EngiiiiiNERD",
    Website: "",
  },
  {
    id: "40",
    Name: "Soham Roy",
    Photo: "images/Members/Soham Roy.jpg",
    Profile: "Algos",
    Year: "All",
    LinkedIn: "https://www.linkedin.com/in/sohamroy15",
    Github: "https://www.github.com/wolflegend99",
    Website: "",
  },
  {
    id: "41",
    Name: "Fasith",
    Photo: "images/Members/Fasith Ali.jpeg",
    Profile: "Algos",
    Year: "All",
    LinkedIn: "https://www.linkedin.com/in/fasith/",
    Github: "https://github.com/Fasith",
    Website: "",
  },
  {
    id: "42",
    Name: "Anoop Kumar",
    Photo: "images/Members/Anoop Kumar.jpg",
    Profile: "Algos",
    Year: "All",
    LinkedIn: "https://www.linkedin.com/in/anoop-kumar-51284514b/",
    Github: "https://github.com/kumaranoop900",
    Website: "",
  },
  {
    id: "43",
    Name: "Raj Kuvar Yadav",
    Photo: "images/Members/Raj Kuvar.jpg",
    Profile: "Algos",
    Year: "All",
    LinkedIn: "https://www.linkedin.com/in/raj-kuvar-4ba9b6172",
    Github: "https://github.com/RAJ107",
    Website: "",
  },
  {
    id: "44",
    Name: "Joel Antony Joseph",
    Photo: "images/Members/Joel Antony Joseph.jpg",
    Profile: "Algos",
    Year: "All",
    LinkedIn: "https://www.linkedin.com/in/joel-antony-joseph-97377315b/",
    Github: "https://github.com/JoAMD",
    Website: "",
  },
  {
    id: "45",
    Name: "Suraj Kumar",
    Photo: "images/Members/Suraj Kumar.jpg",
    Profile: "Algos",
    Year: "All",
    LinkedIn: "https://www.linkedin.com/in/suraj-kumar-700860176",
    Github: "",
    Website: "",
  },
  {
    id: "46",
    Name: "Sankalp Gupta",
    Photo: "images/Members/Sankalp Gupta.jpg",
    Profile: "Algos",
    Year: "All",
    LinkedIn: "https://www.linkedin.com/in/sankalp-gupta-42b84118a",
    Github: "https://github.com/i-am-sank",
    Website: "",
  },

  {
    id: "47",
    Name: "Arvinth Saravanan",
    Photo: "images/Members/Arvinth Saravanan.jpg",
    Profile: "Algos",
    Year: "All",
    LinkedIn: "https://www.linkedin.com/in/arvinth-saravanan-3241b0192/",
    Github: "https://github.com/Arvinth-s",
    Website: "",
  },
  {
    id: "48",
    Name: "Harshit Agrawal",
    Photo: "images/Members/Harshit Agrawal.jpeg",
    Profile: "Algos",
    Year: "All",
    LinkedIn: "https://www.linkedin.com/in/harshit-agrawal-48b74a174/",
    Github: "https://github.com/HarshitCodex",
    Website: "",
  },
  {
    id: "49",
    Name: "Venkataraman V",
    Photo: "images/Members/Venkataraman V.jpeg",
    Profile: "Algos",
    Year: "All",
    LinkedIn: "https://www.linkedin.com/in/venkataraman-v-392090193/",
    Github: "https://github.com/Venkataraman8",
    Website: "",
  },

  {
    id: "52",
    Name: "Anurag Tiwari",
    Photo: "images/Members/Anurag Tiwari.jpeg",
    Profile: "Algos",
    Year: "All",
    LinkedIn: "https://www.linkedin.com/in/anurag-tiwari-25786a176",
    Github: "https://github.com/Anu705",
    Website: "",
  },
  {
    id: "53",
    Name: "Ashish Singh",
    Photo: "images/Members/Ashish Singh.jpg",
    Profile: "Algos",
    Year: "All",
    LinkedIn: "https://www.linkedin.com/in/ashish-singh-19986a176",
    Github: "https://github.com/ashish14012000",
    Website: "",
  },

  {
    id: "54",
    Name: "Nitin Gupta",
    Photo: "images/Members/Nitin Gupta.jpg",
    Profile: "Algos",
    Year: "All",
    LinkedIn: "",
    Github: "https://github.com/nitin0280",
    Website: "",
  },
  {
    id: "55",
    Name: "Ritik Mittal",
    Photo: "images/Members/Ritik Mittal.jpeg",
    Profile: "Algos",
    Year: "All",
    LinkedIn: "https://linkedin.com/in/mittalritik365",
    Github: "https://github.com/ritikmittal",
    Website: "",
  },
  {
    id: "56",
    Name: "Rishab Nahar",
    Photo: "images/Members/Rishab Nahar.jpg",
    Profile: "Algos",
    Year: "All",
    LinkedIn: "",
    Github: "https://github.com/rishab-nahar",
    Website: "",
  },
  {
    id: "57",
    Name: "Satyarth Pandey",
    Photo: "images/Members/Satyarth Pandey.jpg",
    Profile: "Algos",
    Year: "All",
    LinkedIn: "https://www.linkedin.com/in/satyarth-pandey-42a6021a4",
    Github: "https://github.com/satyarth413",
    Website: "",
  },
  {
    id: "58",
    Name: "Sobhagya Singh Dewal",
    Photo: "images/Members/Sobhagya Singh Dewal.jpg",
    Profile: "Algos",
    Year: "All",
    LinkedIn: "",
    Github: "",
    Website: "",
  },
  {
    id: "59",
    Name: "Rhithick Murali",
    Photo: "images/Members/Rhithick .M.jpg",
    Profile: "Algos",
    Year: "All",
    LinkedIn: "https://www.linkedin.com/in/rhithick-murali-634154191",
    Github: "https://github.com/Rhithick02",
    Website: "",
  },

  {
    id: "60",
    Name: "Priyanka Singh",
    Photo: "images/Members/Priyanka Singh.jpg",
    Profile: "Algos",
    Year: "All",
    LinkedIn: "https://www.linkedin.com/in/priyanka-singh-8598761a1/",
    Github: "https://github.com/priyandroid",
    Website: "",
  },
  {
    id: "61",
    Name: "Shivam Pradhan",
    Photo: "images/Members/Shivam Pradhan.jpeg",
    Profile: "Algos",
    Year: "All",
    LinkedIn: "",
    Github: "https://github.com/Shivam1309",
    Website: "",
  },

  {
    id: "62",
    Name: "Preksha Rakhecha",
    Photo: "images/Members/Preksha Rakhecha.JPG",
    Profile: "Algos",
    Year: "All",
    LinkedIn: "https://www.linkedin.com/in/preksha-rakhecha-5b273819b/",
    Github: "https://github.com/preksha121",
    Website: "",
  },
  {
    id: "63",
    Name: "Parvathi Prabhakaran",
    Photo: "images/Members/Parvathi KP.jpg",
    Profile: "Algos",
    Year: "All",
    LinkedIn: "https://www.linkedin.com/in/parvathi-prabhakaran-799744194",
    Github: "https://github.com/parvathikp",
    Website: "",
  },
  {
    id: "64",
    Name: "Manav Mohata",
    Photo: "images/Members/Manav Mohata.jpg",
    Profile: "Algos",
    Year: "All",
    LinkedIn: "https://www.linkedin.com/in/manav-mohata-2ba778190/",
    Github: "https://github.com/manav-06",
    Website: "",
  },
  {
    id: "65",
    Name: "Jack Samuel",
    Photo: "images/new-core/jack.jpg",
    Profile: "Tronix",
    Year: "All",
    LinkedIn: "https://www.linkedin.com/in/jacksamuel98/",
    Github: "",
    Website: "",
  },

  {
    id: "66",
    Name: "Mukesh Gandhi",
    Photo: "images/Members/Mukesh Gandhi.jpg",
    Profile: "Tronix",
    Year: "All",
    LinkedIn: "https://www.linkedin.com/in/mukesh-gandhi-8b7939128",
    Github: "https://github.com/MukkeshGandhi09",
    Website: "",
  },
  {
    id: "67",
    Name: "Aditya R",
    Photo: "images/Members/Aditya Ravi.jpg",
    Profile: "Tronix",
    Year: "All",
    LinkedIn: "https://www.linkedin.com/in/aditya-ravichander-b2584b178",
    Github: "https://github.com/adityaravichander",
    Website: "",
  },
  {
    id: "68",
    Name: "Akil M",
    Photo: "images/Members/Akil M.jpg",
    Profile: "Tronix",
    Year: "All",
    LinkedIn: "https://www.linkedin.com/in/akil-m/",
    Github: "https://github.com/akilm",
    Website: "",
  },
  {
    id: "69",
    Name: "Aditya Kumar Singh",
    Photo: "images/Members/Aditya Singh.jpg",
    Profile: "Tronix",
    Year: "All",
    LinkedIn: "https://www.linkedin.com/in/aditya-kumar-singh-645996152/",
    Github: "https://github.com/adityasingh3007",
    Website: "https://adityasingh3007.github.io/",
  },

  {
    id: "70",
    Name: "Kathirvel Rajan B",
    Photo: "images/Members/CBK - kathirvel rajan.jpeg",
    Profile: "Tronix",
    Year: "All",
    LinkedIn: "https://www.linkedin.com/in/kathirvelrajan22112002/",
    Github: "https://github.com/cbkathir",
    Website: "",
  },
  {
    id: "71",
    Name: "Ruphan S",
    Photo: "images/Members/Ruphan S.jpg",
    Profile: "Tronix",
    Year: "All",
    LinkedIn: "https://www.linkedin.com/in/ruphan-s-37412673",
    Github: "https://github.com/ruphan",
    Website: "",
  },

  {
    id: "72",
    Name: "Manu Aatitya R P",
    Photo: "images/Members/Manu Aatitya.jpg",
    Profile: "Tronix",
    Year: "All",
    LinkedIn: "https://www.linkedin.com/in/manu-aatitya-r-p-78457412b/",
    Github: "https://github.com/manuaatitya",
    Website: "",
  },
  {
    id: "73",
    Name: "Sudharsan S",
    Photo: "images/Members/Sudharsan Sundararaj.jpeg",
    Profile: "Tronix",
    Year: "All",
    LinkedIn: "https://www.linkedin.com/in/sudharsan-s-1a7a1317b/",
    Github: "https://github.com/sudharsan2000",
    Website: "",
  },
  {
    id: "74",
    Name: "S P Sharan",
    Photo: "images/Members/Sharan SP.jpg",
    Profile: "Tronix",
    Year: "All",
    LinkedIn: "https://www.linkedin.com/in/sharan-sp-05735a168",
    Github: "https://github.com/Syzygianinfern0",
    Website: "",
  },
  {
    id: "75",
    Name: "Anbuselvan D",
    Photo: "images/Members/Anbu Selvan.jpeg",
    Profile: "Tronix",
    Year: "All",
    LinkedIn: "https://ca.linkedin.com/in/anbu52",
    Github: "https://github.com/anbu52",
    Website: "",
  },
  {
    id: "76",
    Name: "Kumar Gaurav Singh",
    Photo: "images/Members/Gaurav Singh.jpg",
    Profile: "Tronix",
    Year: "All",
    LinkedIn: "https://www.linkedin.com/in/gaurav-singh-0b056117b",
    Github: "https://github.com/GauravSingh789",
    Website: "",
  },
  {
    id: "77",
    Name: "Kirthika Srinivasan ",
    Photo: "images/Members/Kirthika Srinivasan.jpg",
    Profile: "Tronix",
    Year: "All",
    LinkedIn: "https://www.linkedin.com/in/kirthika-srinivasan-6a9614181",
    Github: "https://github.com/kirthi-ka",
    Website: "",
  },
  {
    id: "78",
    Name: "Anagha Sethuraman",
    Photo: "images/Members/Anagha Sethuraman.jpg",
    Profile: "Tronix",
    Year: "All",
    LinkedIn: "https://www.linkedin.com/in/anagha-sethuraman-192148179/",
    Github: "https://github.com/AnaghaSethuraman",
    Website: "",
  },
  {
    id: "79",
    Name: "Akshaya Subramanian",
    Photo: "images/Members/Akshaya Subramanian.jpeg",
    Profile: "Tronix",
    Year: "All",
    LinkedIn: "https://www.linkedin.com/in/akshaya-subramanian-a6a609185/",
    Github: "https://github.com/AkshayaCSubramanian",
    Website: "",
  },
  {
    id: "80",
    Name: "Miriam Santhosh Kadavan",
    Photo: "images/Members/Miriam.jpg",
    Profile: "Tronix",
    Year: "All",
    LinkedIn: "https://www.linkedin.com/in/miriam-santhosh-kadavan-30927a193/",
    Github: "https://github.com/Githubmsk",
    Website: "",
  },

  {
    id: "81",
    Name: "Himanshu Nandan",
    Photo: "images/Members/Himanshu Nandan.jpg",
    Profile: "Tronix",
    Year: "All",
    LinkedIn: "https://www.linkedin.com/in/himanshu-nandan-4b628a18a",
    Github: "https://github.com/himanshunandan292",
    Website: "",
  },
  {
    id: "82",
    Name: "Manu S",
    Photo: "images/Members/Manu Sekar.jpeg",
    Profile: "Tronix",
    Year: "All",
    LinkedIn: "https://www.linkedin.com/in/manu-sekar-9824351b7/",
    Github: "https://github.com/Manu-Sekar",
    Website: "",
  },
  {
    id: "83",
    Name: "P M Venkata Nagarjun",
    Photo: "images/Members/Venkata Nagarjun P M.jpeg",
    Profile: "Tronix",
    Year: "All",
    LinkedIn: "https://www.linkedin.com/in/venkata-nagarjun-p-m-57190b19a/",
    Github: "https://github.com/Arjun191",
    Website: "",
  },
  {
    id: "84",
    Name: "Ishikaa Lunawat",
    Photo: "images/Members/Ishikaa Lunawat.jpg",
    Profile: "Tronix",
    Year: "All",
    LinkedIn: "https://www.linkedin.com/in/ishikaa-lunawat-776241193",
    Github: "https://github.com/ishikaa25",
    Website: "",
  },
  {
    id: "85",
    Name: "V Prakash",
    Photo: "images/Members/V Prakash.jpeg",
    Profile: "Tronix",
    Year: "All",
    LinkedIn: "",
    Github: "https://github.com/prakash2708",
    Website: "",
  },
  {
    id: "86",
    Name: "Shankar Utthandy V",
    Photo: "images/Members/Shankar Utthandy V.jpg",
    Profile: "Tronix",
    Year: "All",
    LinkedIn: "",
    Github: "",
    Website: "",
  },
  {
    id: "87",
    Name: "G Arvindaksha",
    Photo: "images/Members/Arvindaksha G.jpg",
    Profile: "Tronix",
    Year: "All",
    LinkedIn: "https://www.linkedin.com/in/arvindaksha-g-15622a1a8/",
    Github: "https://github.com/Arvindaksha",
    Website: "",
  },
  {
    id: "88",
    Name: "Arunesh Saddish",
    Photo: "images/Members/Arunesh Saddish.jpeg",
    Profile: "Tronix",
    Year: "All",
    LinkedIn: "https://www.linkedin.com/in/arunesh-saddish-26747519a/",
    Github: "https://github.com/arunesh006",
    Website: "",
  },
  {
    id: "89",
    Name: "Visweswaran B",
    Photo: "images/Members/B Visweswaran.jpg",
    Profile: "Tronix",
    Year: "All",
    LinkedIn: "https://www.linkedin.com/in/visweswaran-b-1675271b4",
    Github: "https://github.com/Vichu-31101",
    Website: "",
  },
  {
    id: "90",
    Name: "Sree Ganesh TN",
    Photo: "images/Members/Sree Ganesh.jpg",
    Profile: "Tronix",
    Year: "All",
    LinkedIn: "",
    Github: "https://github.com/SreeGaneshTN",
    Website: "",
  },
  {
    id: "91",
    Name: "Varshini Priyaa",
    Photo: "images/Members/Varshini Priyaa.jpeg",
    Profile: "Tronix",
    Year: "All",
    LinkedIn:
      "https://www.linkedin.com/in/varshini-priyaa-senthilnathan-83661314a/",
    Github: "https://github.com/varshinisn",
    Website: "",
  },
  {
    id: "92",
    Name: "Vignesh S",
    Photo: "images/Members/Vignesh S.jpeg",
    Profile: "Tronix",
    Year: "All",
    LinkedIn: "`https://www.linkedin.com/in/vignesh-s-3754311b7/",
    Github: "https://github.com/VickyRDK",
    Website: "",
  },
  {
    id: "93",
    Name: "Vivek Malviya",
    Photo: "images/Members/Vivek Malviya.jpg",
    Profile: "Tronix",
    Year: "All",
    LinkedIn: "https://www.linkedin.com/in/vivek-malviya-a10b141b6/",
    Github: "https://github.com/VivekMal29",
    Website: "",
  },
  {
    id: "94",
    Name: "A.Shanmuga Sundaram",
    Photo: "images/Members/Shanmuga Sundaram.jpg",
    Profile: "Tronix",
    Year: "All",
    LinkedIn:
      "https://www.linkedin.com/in/shanmuga-sundaram-5983271b3?lipi=urn%3Ali%3Apage%3Ad_flagship3_profile_view_base_contact_details%3BYrts7jF1SXqUkntP2v4VhA%3D%3D",
    Github: "https://github.com/shan2501",
    Website: "",
  },
  {
    id: "95",
    Name: "N Srikrishna",
    Photo: "images/Members/SrikrishnaN.jpg",
    Profile: "Tronix",
    Year: "All",
    LinkedIn: "https://www.linkedin.com/in/srikrishna-neelakantan-5751b7120",
    Github: "https://github.com/2001srikrishna",
    Website: "",
  },
  {
    id: "96",
    Name: "Surya Thanush",
    Photo: "images/Members/Surya Thanush.jpeg",
    Profile: "Tronix",
    Year: "All",
    LinkedIn: "",
    Github: "https://github.com/suryathanush",
    Website: "",
  },
  {
    id: "97",
    Name: "Himanshu Nandan",
    Photo: "images/Members/Himanshu Nandan.jpg",
    Profile: "Tronix",
    Year: "All",
    LinkedIn: "https://www.linkedin.com/in/himanshu-nandan-4b628a18a",
    Github: "https://github.com/himanshunandan292",
    Website: "",
  },
  {
    id: "98",
    Name: "Arijit Biswas",
    Photo: "images/Members/Arijit Biswas.jpg",
    Profile: "App Dev",
    Year: "All",
    LinkedIn: "https://www.linkedin.com/in/arijit-biswas-b7a85a98",
    Github: "https://github.com/arijitbiswasraj/",
    Website: "",
  },
  {
    id: "99",
    Name: "Disha Raj",
    Photo: "images/Members/Disha Raj.jpeg",
    Profile: "App Dev",
    Year: "All",
    LinkedIn: "https://www.linkedin.com/in/disha-raj-284a05116",
    Github: "https://github.com/DishaRaj",
    Website: "",
  },
  {
    id: "100",
    Name: "Shivam Tiwari",
    Photo: "images/Members/Shivam Tiwari.jpg",
    Profile: "App Dev",
    Year: "All",
    LinkedIn: "https://www.linkedin.com/in/shivam-tiwari-32018b175",
    Github: "https://github.com/shivamtiwari841797",
    Website: "",
  },
  {
    id: "101",
    Name: "Vaibhav Bairagi",
    Photo: "images/Members/Vaibhav Bairagi.jpg",
    Profile: "App Dev",
    Year: "All",
    LinkedIn: "https://www.linkedin.com/in/vaibhav-bairagi-a6ab97161",
    Github: "https://github.com/Vaibhavbairagi",
    Website: "",
  },
  {
    id: "102",
    Name: "Amogh J",
    Photo: "images/Members/Amogh Jahagirdar.jpg",
    Profile: "App Dev",
    Year: "All",
    LinkedIn: "https://www.linkedin.com/in/amoghjahagirdar/",
    Github: "https://github.com/amogh-jrules",
    Website: "https://amogh-jrules.github.io",
  },
  {
    id: "103",
    Name: "Nitin More",
    Photo: "images/Members/Nitin More.jpg",
    Profile: "App Dev",
    Year: "All",
    LinkedIn: "https://www.linkedin.com/in/nitin-more/",
    Github: "https://github.com/NitinMore7",
    Website: "",
  },
  {
    id: "104",
    Name: "Ark Srivastava",
    Photo: "images/Members/Ark  Srivatsvava.jpg",
    Profile: "App Dev",
    Year: "All",
    LinkedIn: "https://www.linkedin.com/in/ark-srivastava-252542160",
    Github: "https://github.com/rarsahki",
    Website: "",
  },
  {
    id: "105",
    Name: "Goutham C M",
    Photo: "images/Members/Goutham CM.jpeg",
    Profile: "App Dev",
    Year: "All",
    LinkedIn: "https://www.linkedin.com/in/goutham-c-m-5a0621154/",
    Github: "https://github.com/gouthamcm",
    Website: "",
  },
  {
    id: "106",
    Name: "Ayush Singh",
    Photo: "images/Members/Ayush Singh.jpg",
    Profile: "App Dev",
    Year: "All",
    LinkedIn: "https://www.linkedin.com/in/ayushsinghs/",
    Github: "https://github.com/ayush547",
    Website: "",
  },
  {
    id: "107",
    Name: "Naren Sairam",
    Photo: "images/Members/Naren Sairam.jpg",
    Profile: "App Dev",
    Year: "All",
    LinkedIn: "https://www.linkedin.com/in/naren-sairam-941739173",
    Github: "https://github.com/nsi319",
    Website: "",
  },
  {
    id: "108",
    Name: "Madhav Aggarwal",
    Photo: "images/Members/Madhav Aggarwal.jpg",
    Profile: "App Dev",
    Year: "All",
    LinkedIn: "https://www.linkedin.com/in/madhav-aggarwal-b16180181/",
    Github: "https://github.com/madhavaggar",
    Website: "",
  },
  {
    id: "109",
    Name: "Harshit Singh",
    Photo: "images/Members/Harshit Singh.jpg",
    Profile: "App Dev",
    Year: "All",
    LinkedIn: "https://www.linkedin.com/in/harshit-singh-83110a193/",
    Github: "https://github.com/LightHarshit",
    Website: "",
  },
  {
    id: "110",
    Name: "Khushali Patel",
    Photo: "images/Members/Khushali Patel.jpg",
    Profile: "App Dev",
    Year: "All",
    LinkedIn: "https://www.linkedin.com/in/khushali-patel-92b182179",
    Github: "https://github.com/khushali259",
    Website: "",
  },
  {
    id: "111",
    Name: "Isha Waghulde",
    Photo: "images/Members/Isha Waghulde.jpg",
    Profile: "App Dev",
    Year: "All",
    LinkedIn: "https://www.linkedin.com/in/isha-waghulde-4529aa17b",
    Github: "https://github.com/ishawaghulde.",
    Website: "",
  },
  {
    id: "112",
    Name: "S P Srinidhi",
    Photo: "images/Members/Srinidhi.jpg",
    Profile: "App Dev",
    Year: "All",
    LinkedIn: "http://www.linkedin.com/in/srinidhi-s-p-b005b4171",
    Github: "https://github.com/Srinidhi2000",
    Website: "",
  },

  {
    id: "113",
    Name: "Abhinav Kothari",
    Photo: "images/Members/Abhinav Kothari.jpg",
    Profile: "App Dev",
    Year: "All",
    LinkedIn: "https://www.linkedin.com/in/abhinav-kothari-67045b199",
    Github: "https://github.com/AK-Zero",
    Website: "",
  },
  {
    id: "114",
    Name: "Gokul P",
    Photo: "images/Members/Gokul Palaniappan.jpg",
    Profile: "App Dev",
    Year: "All",
    LinkedIn: "https://www.linkedin.com/in/gokul-p-2b174a197/",
    Github: "https://github.com/Gokul-31",
    Website: "",
  },
  {
    id: "115",
    Name: "Haemanth V",
    Photo: "images/Members/Haemanth V.jpg",
    Profile: "App Dev",
    Year: "All",
    LinkedIn: "https://www.linkedin.com/in/haemanth-v-951176191",
    Github: "https://github.com/Haemanth-V",
    Website: "",
  },
  {
    id: "116",
    Name: "Anand Pandey",
    Photo: "images/Members/Anand Pandey.jpeg",
    Profile: "App Dev",
    Year: "All",
    LinkedIn: "https://www.linkedin.com/in/anand-pandey6599/",
    Github: "https://github.com/Anand-oops",
    Website: "https://www.instagram.com/anand.pandey__/?hl=en",
  },
  {
    id: "117",
    Name: "Vaasu Gambhir",
    Photo: "images/Members/Vaasu Gambhir.jpg",
    Profile: "App Dev",
    Year: "All",
    LinkedIn: "https://www.linkedin.com/in/vaasu-gambhir-5939b5191/",
    Github: "https://github.com/Vaasuawesome7",
    Website: "",
  },
  {
    id: "118",
    Name: "Dharun Vaibhav U",
    Photo: "images/Members/Dharun Vaibhav U.jpeg",
    Profile: "App Dev",
    Year: "All",
    LinkedIn: "https://www.linkedin.com/in/dharun-vaibhav-u-081b001a1/",
    Github: "https://github.com/Dharun1704",
    Website: "",
  },
  {
    id: "119",
    Name: "Sanjeev Vijayakumar",
    Photo: "images/Members/Sanjeev Vijayakumar.jpg",
    Profile: "App Dev",
    Year: "All",
    LinkedIn: "https://www.linkedin.com/in/sanjeev-vijayakumar-060801/",
    Github: "https://github.com/sanjeevmax6/",
    Website: "",
  },
  {
    id: "120",
    Name: "Ankur Sinha",
    Photo: "images/Members/Ankur Sinha.jpg",
    Profile: "App Dev",
    Year: "All",
    LinkedIn: "https://www.linkedin.com/in/ankur-sinha-811653188",
    Github: "https://github.com/ankursinha03",
    Website: "",
  },

  {
    id: "121",
    Name: "R.Harshavardhan",
    Photo: "images/Members/Harshavardhan Ravichandran.jpg",
    Profile: "App Dev",
    Year: "All",
    LinkedIn: "https://www.linkedin.com/in/harshavardhan-r-85393310a",
    Github: "https://github.com/HR-5",
    Website: "",
  },

  // Exception
  {
    id: "122",
    Name: "Rishabh Taparia",
    Photo: "images/Members/Rishabh Taparia.jpg",
    Profile: "Web Dev",
    Year: "All",
    LinkedIn: "https://www.linkedin.com/in/rishabh-t-837751b8",
    Github: "https://github.com/rt1301",
    Website: "",
  },
  {
    id: "123",
    Name: "Aryan Wadhavekar",
    Photo: "images/Members/Aryan Wadhavekar.jpg",
    Profile: "App Dev",
    Year: "All",
    LinkedIn: "https://www.linkedin.com/in/aryan-wadhavekar-9ab63b1b2",
    Github: "https://github.com/aryanmw",
    Website: "",
  },
  {
    id: "124",
    Name: "Arihant Banthia",
    Photo: "images/Members/Arihant.jpg",
    Profile: "Web Dev",
    Year: "All",
    Linkedin: "https://www.linkedin.com/in/arihant-banthia-834343130/",
    Github: "https://github.com/sachajoy",
  },
  {
    id: "125",
    Name: "Adithya K Krishna",
    Photo: "images/Members/Adithya K Krishna.jpg",
    Profile: "Tronix",
    Year: "All",
    LinkedIn: "https://www.linkedin.com/in/adithya-k-krishna-3a6087193/",
    Github: "https://github.com/AdithyaK243",
    Website: "",
  },
  {
    id: "126",
    Name: "Siddharth Rao A",
    Photo: "images/Members/Siddharth Rao A.jpg",
    Profile: "Tronix",
    Year: "All",
    LinkedIn: "https: //www.linkedin.com/in/siddharth-rao-a-b3b140198",
    Github: "https://github.com/SiddharthRaoA",
    Website: "",
  },
  {
    id: "127",
    Name: "Premkumar N",
    Photo: "images/Members/Premkumar.jpg",
    Profile: "Tronix",
    Year: "All",
    LinkedIn: "https://www.linkedin.com/in/prem-kumar-6ba457136/",
    Github: "https://github.com/pk1510/",
    Website: "",
  },
];
