export const Profile = ["Tronix", "Web Dev", "App Dev", "Algos"];

export const Year = [
  "All",
  "B tech 4th year",
  "B tech 3rd Year",
  "B tech 2nd Year",
];

export const members = [
  // {
  //   id: "1",
  //   Name: "Rishav Roy",
  //   Photo: "images/Members/Rishav Roy.jpg",
  //   Profile: "Web Dev",
  //   Year: "B tech 4th year",
  //   LinkedIn: "https://www.linkedin.com/in/rishav-roy-bba81813b/",
  //   Github: "https://github.com/rishavroy97/",
  //   Website: "",
  // },
  // {
  //   id: "2",
  //   Name: "Benedict Florance",
  //   Photo: "images/Members/Benedict Florance.jpeg",
  //   Profile: "Web Dev",
  //   Year: "B tech 4th year",
  //   LinkedIn: "https://www.linkedin.com/in/benedictflorance/",
  //   Github: "https://github.com/benedictflorance",
  //   Website: "https://benedictflorance.github.io",
  // },
  // {
  //   id: "3",
  //   Name: "Somesh Sundaram",
  //   Photo: "images/Members/Somesh Sundaram.jpg",
  //   Profile: "Web Dev",
  //   Year: "B tech 4th year",
  //   LinkedIn: "",
  //   Github: "",
  //   Website: "",
  // },
  // {
  //   id: "4",
  //   Name: "Swathi Dhamodaran",
  //   Photo: "images/Members/Swathi Dhamodaran.jpg",
  //   Profile: "Web Dev",
  //   Year: "B tech 4th year",
  //   LinkedIn: "https://www.linkedin.com/in/swathi-dhamodaran-8b9053b5",
  //   Github: "",
  //   Website: "",
  // },
  // {
  //   id: "5",
  //   Name: "Saravanan T",
  //   Photo: "images/Members/Saravanan Thanu.jpg",
  //   Profile: "Web Dev",
  //   Year: "B tech 4th year",
  //   LinkedIn: "",
  //   Github: "https://github.com/saranthn",
  //   Website: "",
  // },
  // {
  //   id: "6",
  //   Name: "Sudarshan",
  //   Photo: "images/Members/Sudarshan Parthasarathy.jpg",
  //   Profile: "Web Dev",
  //   Year: "B tech 4th year",
  //   LinkedIn: "",
  //   Github: "",
  //   Website: "",
  // },
  {
    id: "7",
    Name: "Kishore",
    Photo: "images/Members/Kishore V.jpg",
    Profile: "Web Dev",
    Year: "B tech 4th year",
    LinkedIn: "https://www.linkedin.com/in/kishore-v-a006ab153/",
    Github: "https://github.com/Kishorehere",
    Website: "",
  },
  {
    id: "8",
    Name: "S Raghul",
    Photo: "images/Members/Raghul Sivavenkatesh.jpg",
    Profile: "Web Dev",
    Year: "B tech 4th year",
    LinkedIn: "https://www.linkedin.com/in/sraghul127",
    Github: "https://github.com/Raghul127",
    Website: "https://raghul127.github.io/",
  },
  {
    id: "9",
    Name: "P Naveena",
    Photo: "images/Members/Naveena.jpg",
    Profile: "Web Dev",
    Year: "B tech 4th year",
    LinkedIn: "https://www.linkedin.com/in/na899",
    Github: "https://github.com/na899",
    Website: "",
  },
  {
    id: "10",
    Name: "Vishal Saranathan",
    Photo: "images/Members/Vishal Saranathan.jpg",
    Profile: "Web Dev",
    Year: "B tech 4th year",
    LinkedIn: "https://www.linkedin.com/in/vishal-s-126000145/",
    Github: "https://github.com/VishalS99",
    Website: "",
  },

  {
    id: "12",
    Name: "Mohamed Sohail",
    Photo: "images/Members/Mohammed Sohail.jpg",
    Profile: "Web Dev",
    Year: "B tech 4th year",
    LinkedIn: "https://www.linkedin.com/in/mohamedsohail/",
    Github: "https://github.com/kamikazechaser",
    Website: "https:kamikazechaser.github.io",
  },
  {
    id: "13",
    Name: "Prakhar Singh",
    Photo: "images/Members/Prakhar Singh.jpg",
    Profile: "Web Dev",
    Year: "B tech 4th year",
    LinkedIn: "https://www.linkedin.com/in/prakhar-singh-852110173/",
    Github: "https://github.com/prakhar242",
    Website: "",
  },
  {
    id: "14",
    Name: "N Praveen Chandhar",
    Photo: "images/Members/N Praveen Chandhar.jpg",
    Profile: "Web Dev",
    Year: "B tech 4th year",
    LinkedIn: "https://www.linkedin.com/in/praveen27/",
    Github: "https://github.com/gigatesseract/",
    Website: "https://gigatesseract.github.io/",
  },
  {
    id: "15",
    Name: "Joel Johnson",
    Photo: "images/Members/Joel Johnson.jpeg",
    Profile: "Web Dev",
    Year: "B tech 4th year",
    LinkedIn: "https://www.linkedin.com/in/joel-johnson-36694015b/",
    Github: "https://github.com/quantum-jo",
    Website: "joeljohnson.me",
  },
  {
    id: "16",
    Name: "Kamalesh Palanisamy",
    Photo: "images/Members/Kamalesh Palanisamy.jpg",
    Profile: "Web Dev",
    Year: "B tech 4th year",
    LinkedIn: "https://www.linkedin.com/in/kamalesh-palanisamy-2b5265149/",
    Github: "https://github.com/kamalesh0406",
    Website: "http://www.kamaleshp.com",
  },
  {
    id: "17",
    Name: "Anish C ",
    Photo: "images/Members/Chakkirala Anish.jpg",
    Profile: "Web Dev",
    Year: "B tech 3rd Year",
    LinkedIn: "https://donothaveone.com",
    Github: "https://github.com/chakki1234",
    Website: "",
  },
  {
    id: "18",
    Name: "Anjaneya Tripathi",
    Photo: "images/Members/Anjaneya Tripathi.jpeg",
    Profile: "Web Dev",
    Year: "B tech 3rd Year",
    LinkedIn: "https://www.linkedin.com/in/anjaneya-tripathi-610234183/",
    Github: "https://github.com/AnjaneyaTripathi",
    Website: "",
  },
  {
    id: "19",
    Name: "Thrishik Senthilkumar",
    Photo: "images/Members/Thrishik Senthilkumar.jpg",
    Profile: "Web Dev",
    Year: "B tech 3rd Year",
    LinkedIn: "https://in.linkedin.com/in/thrishik-senthilkumar-123918176",
    Github: "https://github.com/thrishik7",
    Website: "",
  },
  {
    id: "21",
    Name: "Barath Kumar S",
    Photo: "images/Members/Barath.png",
    Profile: "Web Dev",
    Year: "B tech 3rd Year",
    LinkedIn: "https://linkedin.com/in/barath1999",
    Github: "https://www.github.com/barath99",
    Website: "https://barath99.github.io",
  },
  {
    id: "23",
    Name: "Smrithi Prakash",
    Photo: "images/Members/Smrithi.png",
    Profile: "Web Dev",
    Year: "B tech 3rd Year",
    LinkedIn: "https://linkedin.com/in/smrithi-prakash-452173193",
    Github: "https://github.com/Smrithi23",
    Website: "",
  },
  {
    id: "24",
    Name: "Jerry J",
    Photo: "images/Members/Jerry.png",
    Profile: "Web Dev",
    Year: "B tech 3rd Year",
    LinkedIn: "https://www.linkedin.com/in/jerry-j-89aa52174/",
    Github: "https://github.com/Hank-learner",
    Website: "",
  },
  // {
  //   id: "25",
  //   Name: "Rajat Bhatta",
  //   Photo: "images/Members/Rajat Bhatta.jpg",
  //   Profile: "Algos",
  //   Year: "B tech 4th year",
  //   LinkedIn: "https://www.linkedin.com/in/rajat-bhatta",
  //   Github: "https://github.com/barry-1928",
  //   Website: "",
  // },
  {
    id: "26",
    Name: "Mritunjay Kumar",
    Photo: "images/Members/Mritunjay Kumar.jpg",
    Profile: "Algos",
    Year: "MCA 2nd year",
    LinkedIn: "https://www.linkedin.com/in/mritunjay-kumar-a5501b193/",
    Github: "https://github.com/mritunjay583",
    Website: "",
  },
  {
    id: "27",
    Name: "Kundan",
    Photo: "images/Members/Kundan Mandloi.jpg",
    Profile: "Algos",
    Year: "MCA 2nd year",
    LinkedIn: "https://www.linkedin.com/in/kundan-mandloi-078627181/",
    Github: "https://github.com/Kunda31n",
    Website: "",
  },
  {
    id: "28",
    Name: "Harsh Bhadoria",
    Photo: "images/Members/Harsh Bhadoria.jpg",
    Profile: "Algos",
    Year: "MCA 2nd year",
    LinkedIn: "https://www.linkedin.com/in/harsh-bhadoria-989665144/",
    Github: "https://github.com/harshbhadoria011",
    Website: "",
  },
  // {
  //   id: "29",
  //   Name: "Anukul Chand",
  //   Photo: "images/Members/Anukul Chand.jpg",
  //   Profile: "Algos",
  //   Year: "B tech 4th year",
  //   LinkedIn: "https://www.linkedin.com/in/anukul-chand-199369148/",
  //   Github: "https://github.com/cyberfreak5725",
  //   Website: "",
  // },
  // {
  //   id: "30",
  //   Name: "Shivani Chander",
  //   Photo: "images/Members/Shivani Chander.jpg",
  //   Profile: "Algos",
  //   Year: "B tech 4th year",
  //   LinkedIn: "https://www.linkedin.com/in/shivanichander/",
  //   Github: "https://github.com/shivanichander",
  //   Website: "",
  // },
  // {
  //   id: "31",
  //   Name: "Sandip Nair",
  //   Photo: "images/Members/Sandip Nair.jpg",
  //   Profile: "Algos",
  //   Year: "B tech 4th year",
  //   LinkedIn: "https://www.linkedin.com/in/sandipnair/",
  //   Github: "https://github.com/SanNare",
  //   Website: "https://medium.com/@sandipnr0",
  // },
  // {
  //   id: "32",
  //   Name: "Harshit Babbar",
  //   Photo: "images/Members/Harshit Babbar.jpg",
  //   Profile: "Algos",
  //   Year: "B tech 4th year",
  //   LinkedIn: "https://www.linkedin.com/in/harshit-babbar/",
  //   Github: "https://github.com/HarshitNITT",
  //   Website: "",
  // },
  // {
  //   id: "33",
  //   Name: "Rajiv",
  //   Photo: "images/Members/R Rajiv.jpeg",
  //   Profile: "Algos",
  //   Year: "B tech 4th year",
  //   LinkedIn: "https://www.linkedin.com/in/rajiv-ramachandran-51a510166/",
  //   Github: "https://github.com/rRajivramachandran",
  //   Website: "",
  // },
  {
    id: "34",
    Name: "Sri Harsha T.V",
    Photo: "images/Members/Sri Harsha T V.jpeg",
    Profile: "Algos",
    Year: "B tech 4th year",
    LinkedIn: "https://www.linkedin.com/in/sri-harsha-t-v-b7484a157",
    Github: "https://github.com/tvs1998",
    Website: "",
  },
  {
    id: "35",
    Name: "Shiwang Singh",
    Photo: "images/Members/Shivam Tiwari.jpg",
    Profile: "Algos",
    Year: "B tech 4th year",
    LinkedIn: "https://www.linkedin.com/in/shiwang-singh-33941515a",
    Github: "https://github.com/Shiwang9",
    Website: "",
  },
  {
    id: "36",
    Name: "Dhruv Bodani",
    Photo: "images/Members/Dhruv Bodani.jpg",
    Profile: "Algos",
    Year: "B tech 4th year",
    LinkedIn: "https://www.linkedin.com/in/dhruv-bodani-254a2b151",
    Github: "https://github.com/dB2510",
    Website: "",
  },
  {
    id: "37",
    Name: "Arvind Tatiparti",
    Photo: "images/Members/Arvind Tatiparti.jpg",
    Profile: "Algos",
    Year: "B tech 4th year",
    LinkedIn: "https://www.linkedin.com/in/arvindtatiparti/",
    Github: "https://github.com/r0uxt1",
    Website: "",
  },
  {
    id: "38",
    Name: "Aditya Kumar",
    Photo: "images/Members/Aditya Kumar.jpg",
    Profile: "Algos",
    Year: "B tech 4th year",
    LinkedIn: "https://linkedin.com/in/aditya-kumar-8218ab138",
    Github: "https://github.com/kumaraditya1999",
    Website: "",
  },
  {
    id: "39",
    Name: "Harshit Mogalapalli ",
    Photo: "images/Members/Harshit Mogalapalli.jpg",
    Profile: "Algos",
    Year: "B tech 4th year",
    LinkedIn: "https://www.linkedin.com/in/harshit-mogalapalli-44025917b",
    Github: "https://github.com/harshimogalapalli",
    Website: "",
  },
  {
    id: "40",
    Name: "Chidanand Dev Suryawanshi",
    Photo: "images/Members/Chidanand Dev Suryawanshi.jpg",
    Profile: "Algos",
    Year: "B tech 4th year",
    LinkedIn: "https://www.linkedin.com/in/engiiiiinerd",
    Github: "https://github.com/EngiiiiiNERD",
    Website: "",
  },
  {
    id: "41",
    Name: "Soham Roy",
    Photo: "images/Members/Soham Roy.jpg",
    Profile: "Algos",
    Year: "B tech 4th year",
    LinkedIn: "https://www.linkedin.com/in/sohamroy15",
    Github: "https://www.github.com/wolflegend99",
    Website: "",
  },
  {
    id: "42",
    Name: "Fasith",
    Photo: "images/Members/Fasith Ali.jpeg",
    Profile: "Algos",
    Year: "B tech 4th year",
    LinkedIn: "https://www.linkedin.com/in/fasith/",
    Github: "https://github.com/Fasith",
    Website: "",
  },
  {
    id: "43",
    Name: "Anoop Kumar",
    Photo: "images/Members/Anoop Kumar.jpg",
    Profile: "Algos",
    Year: "B tech 4th year",
    LinkedIn: "https://www.linkedin.com/in/anoop-kumar-51284514b/",
    Github: "https://github.com/kumaranoop900",
    Website: "",
  },
  {
    id: "44",
    Name: "Raj Kuvar Yadav",
    Photo: "images/Members/Raj Kuvar.jpg",
    Profile: "Algos",
    Year: "B tech 4th year",
    LinkedIn: "https://www.linkedin.com/in/raj-kuvar-4ba9b6172",
    Github: "https://github.com/RAJ107",
    Website: "",
  },
  {
    id: "45",
    Name: "Joel Antony Joseph",
    Photo: "images/Members/Joel Antony Joseph.jpg",
    Profile: "Algos",
    Year: "B tech 4th year",
    LinkedIn: "https://www.linkedin.com/in/joel-antony-joseph-97377315b/",
    Github: "https://github.com/JoAMD",
    Website: "",
  },
  {
    id: "46",
    Name: "Arvinth Saravanan",
    Photo: "images/Members/Arvinth Saravanan.jpg",
    Profile: "Algos",
    Year: "B tech 3rd Year",
    LinkedIn: "https://www.linkedin.com/in/arvinth-saravanan-3241b0192/",
    Github: "https://github.com/Arvinth-s",
    Website: "",
  },
  {
    id: "47",
    Name: "Harshit Agrawal",
    Photo: "images/Members/Harshit Agrawal.jpeg",
    Profile: "Algos",
    Year: "B tech 3rd Year",
    LinkedIn: "https://www.linkedin.com/in/harshit-agrawal-48b74a174/",
    Github: "https://github.com/HarshitCodex",
    Website: "",
  },
  {
    id: "48",
    Name: "Venkataraman V",
    Photo: "images/Members/Venkataraman V.jpeg",
    Profile: "Algos",
    Year: "B tech 3rd Year",
    LinkedIn: "https://www.linkedin.com/in/venkataraman-v-392090193/",
    Github: "https://github.com/Venkataraman8",
    Website: "",
  },
  {
    id: "49",
    Name: "Adithya K Krishna",
    Photo: "images/Members/Adithya Krishnakumar.jpg",
    Profile: "Algos",
    Year: "B tech 3rd Year",
    LinkedIn: "https://www.linkedin.com/in/adithya-krishnakumar-3a6087193/",
    Github: "https://github.com/AdithyaK243",
    Website: "",
  },
  {
    id: "50",
    Name: "Poorna Subramanian",
    Photo: "images/Members/Poorna subramanian.jpg",
    Profile: "Algos",
    Year: "B tech 3rd Year",
    LinkedIn: "https://www.linkedin.com/in/poorna-subramanian-90924b181",
    Github: "https://github.com/poorna20",
    Website: "",
  },
  {
    id: "51",
    Name: "Anagha Sethuraman",
    Photo: "images/Members/Anagha Sethuraman.jpg",
    Profile: "Algos",
    Year: "B tech 3rd Year",
    LinkedIn: "https://www.linkedin.com/in/anagha-sethuraman-192148179/",
    Github: "https://github.com/AnaghaSethuraman",
    Website: "",
  },
  // {
  //   id: "52",
  //   Name: "Senthur Raj",
  //   Photo: "images/Members/Senthur-Raj - Senthur raj.jpg",
  //   Profile: "Tronix",
  //   Year: "B tech 4th year",
  //   LinkedIn: "https://www.linkedin.com/in/imsenthur/",
  //   Github: "https://github.com/imsenthur",
  //   Website: "",
  // },
  // {
  //   id: "53",
  //   Name: "Shubham Saha",
  //   Photo: "images/Members/Shubham Saha.jpg",
  //   Profile: "Tronix",
  //   Year: "B tech 4th year",
  //   LinkedIn: "https://www.linkedin.com/in/shubhamsaha",
  //   Github: "https://github.com/Helinskii",
  //   Website: "",
  // },
  // {
  //   id: "54",
  //   Name: "Vibashan",
  //   Photo: "images/Members/Vibashan VS.jpg",
  //   Profile: "Tronix",
  //   Year: "B tech 4th year",
  //   LinkedIn: "https://www.linkedin.com/in/vibashan-vs-23321b142/",
  //   Github: "https://github.com/Vibashan",
  //   Website: "",
  // },
  // {
  //   id: "55",
  //   Name: "C Sundara Paripooranan",
  //   Photo: "images/Members/Sundara Paripooranan.jpg",
  //   Profile: "Tronix",
  //   Year: "B tech 4th year",
  //   LinkedIn: " https://www.linkedin.com/in/c-sundara-paripooranan-65343b15b",
  //   Github: "https://github.com/paripooranan",
  //   Website: "",
  // },
  // {
  //   id: "56",
  //   Name: "Abishek K R",
  //   Photo: "images/Members/Abishek K R.jpg",
  //   Profile: "Tronix",
  //   Year: "B tech 4th year",
  //   LinkedIn: "https://www.linkedin.com/in/abishek-ramachandran-81745b126",
  //   Github: "https://github.com/Abishek0398",
  //   Website: "",
  // },
  // {
  //   id: "57",
  //   Name: "D C Vivek",
  //   Photo: "images/Members/Vivek Dc.png",
  //   Profile: "Tronix",
  //   Year: "B tech 4th year",
  //   LinkedIn: "https://www.linkedin.com/in/vivek-dc-35069b141",
  //   Github: "https://www.github.com/dc28vivek",
  //   Website: "",
  // },
  // {
  //   id: "58",
  //   Name: "Abishek R",
  //   Photo: "images/Members/Abishek Rajasekaran.png",
  //   Profile: "Tronix",
  //   Year: "B tech 4th year",
  //   LinkedIn: "https://www.linkedin.com/in/abishek-r-468183178/",
  //   Github: "https://github.com/abishek27",
  //   Website: "",
  // },
  // {
  //   id: "59",
  //   Name: "Chockalingam",
  //   Photo: "images/Members/Chocka Lingam.jpg",
  //   Profile: "Tronix",
  //   Year: "B tech 4th year",
  //   LinkedIn: "https://www.linkedin.com/in/chocka-lingam-4bb803148",
  //   Github: "https://bitbucket.org/chocka/",
  //   Website: "",
  // },

  // {
  //   id: "60",
  //   Name: "Bhavya Krishna",
  //   Photo: "images/Members/Bhavya Krishna.jpg",
  //   Profile: "Tronix",
  //   Year: "B tech 4th year",
  //   LinkedIn: "https://www.linkedin.com/in/bhavya-krishna-6277b251",
  //   Github: "https://github.com/BhavyaKrishna",
  //   Website: "",
  // },
  // {
  //   id: "61",
  //   Name: "Aradhana M P",
  //   Photo: "images/Members/Aradhana M P.jpg",
  //   Profile: "Tronix",
  //   Year: "B tech 4th year",
  //   LinkedIn: "https://www.linkedin.com/in/aradhana-mohan-parvathy-64069413a/",
  //   Github: "https://github.com/MPARADHANA",
  //   Website: "",
  // },
  // {
  //   id: "62",
  //   Name: "Amritha S B",
  //   Photo: "images/Members/Amritha Bhaskaran.jpg",
  //   Profile: "Tronix",
  //   Year: "B tech 4th year",
  //   LinkedIn: "https://www.linkedin.com/in/amritha-s-b-43283015b",
  //   Github: "https://github.com/amritha-sb",
  //   Website: "",
  // },
  {
    id: "63",
    Name: "Mukesh Gandhi",
    Photo: "images/Members/Mukesh Gandhi.jpg",
    Profile: "Tronix",
    Year: "B tech 4th year",
    LinkedIn: "https://www.linkedin.com/in/mukesh-gandhi-8b7939128",
    Github: "https://github.com/MukkeshGandhi09",
    Website: "",
  },
  {
    id: "64",
    Name: "Aditya R",
    Photo: "images/Members/Aditya Ravi.jpg",
    Profile: "Tronix",
    Year: "B tech 4th year",
    LinkedIn: "https://www.linkedin.com/in/aditya-ravichander-b2584b178",
    Github: "https://github.com/adityaravichander",
    Website: "",
  },
  {
    id: "65",
    Name: "Akil M",
    Photo: "images/Members/Akil M.jpg",
    Profile: "Tronix",
    Year: "B tech 4th year",
    LinkedIn: "https://www.linkedin.com/in/akil-m/",
    Github: "https://github.com/akilm",
    Website: "",
  },
  {
    id: "66",
    Name: "Aditya Kumar Singh",
    Photo: "images/Members/Aditya Singh.jpg",
    Profile: "Tronix",
    Year: "B tech 4th year",
    LinkedIn: "https://www.linkedin.com/in/aditya-kumar-singh-645996152/",
    Github: "https://github.com/adityasingh3007",
    Website: "https://adityasingh3007.github.io/",
  },
  {
    id: "67",
    Name: "Raj Kumar Bhagat",
    Photo: "images/Members/Raj kumar.jpg",
    Profile: "Tronix",
    Year: "B tech 4th year",
    LinkedIn: "https://www.linkedin.com/in/raj-kumar-bhagat-97b310170/",
    Github: "https://github.com/Rajk0520",
    Website: "",
  },
  {
    id: "68",
    Name: "Kathirvel Rajan B",
    Photo: "images/Members/CBK - kathirvel rajan.jpeg",
    Profile: "Tronix",
    Year: "B tech 4th year",
    LinkedIn: "https://www.linkedin.com/in/kathirvelrajan22112002/",
    Github: "https://github.com/cbkathir",
    Website: "",
  },
  {
    id: "69",
    Name: "Ruphan S",
    Photo: "images/Members/Ruphan S.jpg",
    Profile: "Tronix",
    Year: "B tech 4th year",
    LinkedIn: "https://www.linkedin.com/in/ruphan-s-37412673",
    Github: "https://github.com/ruphan",
    Website: "",
  },
  {
    id: "70",
    Name: "Yash Patel",
    Photo: "images/Members/Yash Patel.png",
    Profile: "Tronix",
    Year: "B tech 4th year",
    LinkedIn: "https://www.linkedin.com/in/yash-patel-29379414a/",
    Github: "https://github.com/ComputerMaestro",
    Website: "",
  },
  {
    id: "71",
    Name: "Manu Aatitya R P",
    Photo: "images/Members/Manu Aatitya.jpg",
    Profile: "Tronix",
    Year: "B tech 4th year",
    LinkedIn: "https://www.linkedin.com/in/manu-aatitya-r-p-78457412b/",
    Github: "https://github.com/manuaatitya",
    Website: "",
  },
  {
    id: "72",
    Name: "Sudharsan S",
    Photo: "images/Members/Sudharsan Sundararaj.jpeg",
    Profile: "Tronix",
    Year: "B tech 3rd Year",
    LinkedIn: "https://www.linkedin.com/in/sudharsan-s-1a7a1317b/",
    Github: "https://github.com/sudharsan2000",
    Website: "",
  },
  {
    id: "73",
    Name: "S P Sharan",
    Photo: "images/Members/Sharan SP.jpg",
    Profile: "Tronix",
    Year: "B tech 3rd Year",
    LinkedIn: "https://www.linkedin.com/in/sharan-sp-05735a168",
    Github: "https://github.com/Syzygianinfern0",
    Website: "",
  },
  {
    id: "74",
    Name: "Anbuselvan D",
    Photo: "images/Members/Anbu Selvan.jpeg",
    Profile: "Tronix",
    Year: "B tech 3rd Year",
    LinkedIn: "https://ca.linkedin.com/in/anbu52",
    Github: "https://github.com/anbu52",
    Website: "",
  },
  {
    id: "75",
    Name: "Kumar Gaurav Singh",
    Photo: "images/Members/Gaurav Singh.jpg",
    Profile: "Tronix",
    Year: "B tech 3rd Year",
    LinkedIn: "https://www.linkedin.com/in/gaurav-singh-0b056117b",
    Github: "https://github.com/GauravSingh789",
    Website: "",
  },
  {
    id: "76",
    Name: "Kirthika Srinivasan ",
    Photo: "images/Members/Kirthika Srinivasan.jpg",
    Profile: "Tronix",
    Year: "B tech 3rd Year",
    LinkedIn: "https://www.linkedin.com/in/kirthika-srinivasan-6a9614181",
    Github: "https://github.com/kirthi-ka",
    Website: "",
  },
  {
    id: "77",
    Name: "Akshaya Subramanian",
    Photo: "images/Members/Akshaya Subramanian.jpeg",
    Profile: "Tronix",
    Year: "B tech 3rd Year",
    LinkedIn: "https://www.linkedin.com/in/akshaya-subramanian-a6a609185/",
    Github: "https://github.com/AkshayaCSubramanian",
    Website: "",
  },
  {
    id: "78",
    Name: "Miriam Santhosh Kadavan",
    Photo: "images/Members/Miriam.jpg",
    Profile: "Tronix",
    Year: "B tech 3rd Year",
    LinkedIn: "https://www.linkedin.com/in/miriam-santhosh-kadavan-30927a193/",
    Github: "https://github.com/Githubmsk",
    Website: "",
  },
  {
    id: "79",
    Name: "Jayamathangi Srinivasan",
    Photo: "images/Members/Jayamathangi Srinivasan.jpg",
    Profile: "Tronix",
    Year: "B tech 3rd Year",
    LinkedIn: "https://www.linkedin.com/in/jayamathangi-s-3464a8184",
    Github: "https://www.github.com/Jayamathangi",
    Website: "",
  },
  {
    id: "80",
    Name: "M Shyam",
    Photo: "images/Members/Shyam Murugan.jpg",
    Profile: "Tronix",
    Year: "B tech 3rd Year",
    LinkedIn: "https://www.linkedin.com/in/shyam-murugan/",
    Github: "https://github.com/shyam-king",
    Website: "",
  },
  {
    id: "81",
    Name: "Sachin Kumar",
    Photo: "images/Members/Sachin Kumar.jpg",
    Profile: "Tronix",
    Year: "B tech 3rd Year",
    LinkedIn: "https://www.linkedin.com/in/sachin-kumar-837b2b17b/",
    Github: "https://github.com/sachin-101",
    Website: "",
  },
  // {
  //   id: "82",
  //   Name: "Rahul Bhope",
  //   Photo: "images/Members/Rahul Bhope.jpg",
  //   Profile: "App Dev",
  //   Year: "B tech 4th year",
  //   LinkedIn: "https://in.linkedin.com/in/rahul-bhope-3a0976130",
  //   Github: "https://github.com/rahulatulbhope",
  //   Website: "https://rahulatulbhope.github.io/",
  // },
  {
    id: "83",
    Name: "Arijit Biswas",
    Photo: "images/Members/Arijit Biswas.jpg",
    Profile: "App Dev",
    Year: "MCA 2nd year",
    LinkedIn: "https://www.linkedin.com/in/arijit-biswas-b7a85a98",
    Github: "https://github.com/arijitbiswasraj/",
    Website: "",
  },
  {
    id: "84",
    Name: "Disha Raj",
    Photo: "images/Members/Disha Raj.jpg",
    Profile: "App Dev",
    Year: "MCA 2nd year",
    LinkedIn: "https://www.linkedin.com/in/disha-raj-284a05116",
    Github: "https://github.com/DishaRaj",
    Website: "",
  },
  {
    id: "85",
    Name: "Shivam Tiwari",
    Photo: "images/Members/Shivam Tiwari.jpg",
    Profile: "App Dev",
    Year: "MCA 2nd year",
    LinkedIn: "https://www.linkedin.com/in/shivam-tiwari-32018b175",
    Github: "https://github.com/shivamtiwari841797",
    Website: "",
  },
  // {
  //   id: "86",
  //   Name: "Abhilasha Nagpal",
  //   Photo: "images/Members/Abhilasha_Nagpal - Abhilasha Nagpal.jpg",
  //   Profile: "App Dev",
  //   Year: "B tech 4th year",
  //   LinkedIn: "https://www.linkedin.com/in/abhilasha-nagpal",
  //   Github: "https://github.com/AbhilashaN",
  //   Website: "",
  // },
  // {
  //   id: "87",
  //   Name: "Rakesh Vaideeswaran",
  //   Photo: "images/Members/Rakesh Vaideeswaran.jpg",
  //   Profile: "App Dev",
  //   Year: "B tech 4th year",
  //   LinkedIn: "https://www.linkedin.com/in/rakesh-v-647481b6",
  //   Github: "https://github.com/RakeshVaideeswaran",
  //   Website: "",
  // },
  {
    id: "88",
    Name: "Vaibhav Bairagi",
    Photo: "images/Members/Vaibhav Bairagi.jpg",
    Profile: "App Dev",
    Year: "B tech 4th year",
    LinkedIn: "https://www.linkedin.com/in/vaibhav-bairagi-a6ab97161",
    Github: "https://github.com/Vaibhavbairagi",
    Website: "",
  },
  {
    id: "89",
    Name: "Amogh J",
    Photo: "images/Members/Amogh Jahagirdar.jpg",
    Profile: "App Dev",
    Year: "B tech 4th year",
    LinkedIn: "https://www.linkedin.com/in/amoghjahagirdar/",
    Github: "https://github.com/amogh-jrules",
    Website: "https://amogh-jrules.github.io",
  },
  {
    id: "90",
    Name: "Nitin More",
    Photo: "images/Members/Nitin More.jpg",
    Profile: "App Dev",
    Year: "B tech 4th year",
    LinkedIn: "https://www.linkedin.com/in/nitin-more/",
    Github: "https://github.com/NitinMore7",
    Website: "",
  },
  {
    id: "91",
    Name: "Ark Srivastava",
    Photo: "images/Members/Ark  Srivatsvava.jpg",
    Profile: "App Dev",
    Year: "B tech 4th year",
    LinkedIn: "https://www.linkedin.com/in/ark-srivastava-252542160",
    Github: "https://github.com/rarsahki",
    Website: "",
  },
  {
    id: "92",
    Name: "Goutham C M",
    Photo: "images/Members/Goutham CM.jpeg",
    Profile: "App Dev",
    Year: "B tech 4th year",
    LinkedIn: "https://www.linkedin.com/in/goutham-c-m-5a0621154/",
    Github: "https://github.com/gouthamcm",
    Website: "",
  },
  {
    id: "93",
    Name: "Ayush Singh",
    Photo: "images/Members/Ayush Singh.jpg",
    Profile: "App Dev",
    Year: "B tech 3rd Year",
    LinkedIn: "https://www.linkedin.com/in/ayushsinghs/",
    Github: "https://github.com/ayush547",
    Website: "",
  },
  {
    id: "94",
    Name: "Naren Sairam",
    Photo: "images/Members/Naren Sairam.jpg",
    Profile: "App Dev",
    Year: "B tech 3rd Year",
    LinkedIn: "https://www.linkedin.com/in/naren-sairam-941739173",
    Github: "https://github.com/nsi319",
    Website: "",
  },
  {
    id: "95",
    Name: "Madhav Aggarwal",
    Photo: "images/Members/Madhav Aggarwal.jpg",
    Profile: "App Dev",
    Year: "B tech 3rd Year",
    LinkedIn: "https://www.linkedin.com/in/madhav-aggarwal-b16180181/",
    Github: "https://github.com/madhavaggar",
    Website: "",
  },
  {
    id: "96",
    Name: "Harshit Singh",
    Photo: "images/Members/Harshit Singh.jpg",
    Profile: "App Dev",
    Year: "B tech 3rd Year",
    LinkedIn: "https://www.linkedin.com/in/harshit-singh-83110a193/",
    Github: "https://github.com/LightHarshit",
    Website: "",
  },
  {
    id: "97",
    Name: "Khushali Patel",
    Photo: "images/Members/Khushali Patel.jpg",
    Profile: "App Dev",
    Year: "B tech 3rd Year",
    LinkedIn: "https://www.linkedin.com/in/khushali-patel-92b182179",
    Github: "https://github.com/khushali259",
    Website: "",
  },
  {
    id: "98",
    Name: "Isha Waghulde",
    Photo: "images/Members/Isha Waghulde.jpg",
    Profile: "App Dev",
    Year: "B tech 3rd Year",
    LinkedIn: "https://www.linkedin.com/in/isha-waghulde-4529aa17b",
    Github: "https://github.com/ishawaghulde.",
    Website: "",
  },
  {
    id: "99",
    Name: "S P Srinidhi",
    Photo: "images/Members/Srinidhi.jpg",
    Profile: "App Dev",
    Year: "B tech 3rd Year",
    LinkedIn: "http://www.linkedin.com/in/srinidhi-s-p-b005b4171",
    Github: "https://github.com/Srinidhi2000",
    Website: "",
  },
  // {
  //   id: "100",
  //   Name: "Rishav Roy",
  //   Photo: "images/Members/Rishav Roy.jpg",
  //   Profile: "Web Dev",
  //   Year: "All",
  //   LinkedIn: "https://www.linkedin.com/in/rishav-roy-bba81813b/",
  //   Github: "https://github.com/rishavroy97/",
  //   Website: "",
  // },
  // {
  //   id: "101",
  //   Name: "Benedict Florance",
  //   Photo: "images/Members/Benedict Florance.jpeg",
  //   Profile: "Web Dev",
  //   Year: "All",
  //   LinkedIn: "https://www.linkedin.com/in/benedictflorance/",
  //   Github: "https://github.com/benedictflorance",
  //   Website: "https://benedictflorance.github.io",
  // },
  // {
  //   id: "102",
  //   Name: "Somesh Sundaram",
  //   Photo: "images/Members/Somesh Sundaram.jpg",
  //   Profile: "Web Dev",
  //   Year: "All",
  //   LinkedIn: "",
  //   Github: "",
  //   Website: "",
  // },
  // {
  //   id: "103",
  //   Name: "Swathi Dhamodaran",
  //   Photo: "images/Members/Swathi Dhamodaran.jpg",
  //   Profile: "Web Dev",
  //   Year: "All",
  //   LinkedIn: "https://www.linkedin.com/in/swathi-dhamodaran-8b9053b5",
  //   Github: "",
  //   Website: "",
  // },
  // {
  //   id: "104",
  //   Name: "Saravanan T",
  //   Photo: "images/Members/Saravanan Thanu.jpg",
  //   Profile: "Web Dev",
  //   Year: "All",
  //   LinkedIn: "",
  //   Github: "https://github.com/saranthn",
  //   Website: "",
  // },
  // {
  //   id: "105",
  //   Name: "Sudarshan",
  //   Photo: "images/Members/Sudarshan Parthasarathy.jpg",
  //   Profile: "Web Dev",
  //   Year: "All",
  //   LinkedIn: "",
  //   Github: "",
  //   Website: "",
  // },
  {
    id: "106",
    Name: "Kishore",
    Photo: "images/Members/Kishore V.jpg",
    Profile: "Web Dev",
    Year: "All",
    LinkedIn: "https://www.linkedin.com/in/kishore-v-a006ab153/",
    Github: "https://github.com/Kishorehere",
    Website: "",
  },
  {
    id: "107",
    Name: "S Raghul",
    Photo: "images/Members/Raghul Sivavenkatesh.jpg",
    Profile: "Web Dev",
    Year: "All",
    LinkedIn: "https://www.linkedin.com/in/sraghul127",
    Github: "https://github.com/Raghul127",
    Website: "https://raghul127.github.io/",
  },
  {
    id: "108",
    Name: "P Naveena",
    Photo: "images/Members/Naveena.jpg",
    Profile: "Web Dev",
    Year: "All",
    LinkedIn: "https://www.linkedin.com/in/na899",
    Github: "https://github.com/na899",
    Website: "",
  },
  {
    id: "109",
    Name: "Vishal Saranathan",
    Photo: "images/Members/Vishal Saranathan.jpg",
    Profile: "Web Dev",
    Year: "All",
    LinkedIn: "https://www.linkedin.com/in/vishal-s-126000145/",
    Github: "https://github.com/VishalS99",
    Website: "",
  },

  {
    id: "110",
    Name: "Mohamed Sohail",
    Photo: "images/Members/Mohammed Sohail.jpg",
    Profile: "Web Dev",
    Year: "All",
    LinkedIn: "https://www.linkedin.com/in/mohamedsohail/",
    Github: "https://github.com/kamikazechaser",
    Website: "https:kamikazechaser.github.io",
  },
  {
    id: "111",
    Name: "Prakhar Singh",
    Photo: "images/Members/Prakhar Singh.jpg",
    Profile: "Web Dev",
    Year: "All",
    LinkedIn: "https://www.linkedin.com/in/prakhar-singh-852110173/",
    Github: "https://github.com/prakhar242",
    Website: "",
  },
  {
    id: "112",
    Name: "N Praveen Chandhar",
    Photo: "images/Members/N Praveen Chandhar.jpg",
    Profile: "Web Dev",
    Year: "All",
    LinkedIn: "https://www.linkedin.com/in/praveen27/",
    Github: "https://github.com/gigatesseract/",
    Website: "https://gigatesseract.github.io/",
  },
  {
    id: "113",
    Name: "Joel Johnson",
    Photo: "images/Members/Joel Johnson.jpeg",
    Profile: "Web Dev",
    Year: "All",
    LinkedIn: "https://www.linkedin.com/in/joel-johnson-36694015b/",
    Github: "https://github.com/quantum-jo",
    Website: "joeljohnson.me",
  },
  {
    id: "114",
    Name: "Kamalesh Palanisamy",
    Photo: "images/Members/Kamalesh Palanisamy.jpg",
    Profile: "Web Dev",
    Year: "All",
    LinkedIn: "https://www.linkedin.com/in/kamalesh-palanisamy-2b5265149/",
    Github: "https://github.com/kamalesh0406",
    Website: "http://www.kamaleshp.com",
  },
  {
    id: "115",
    Name: "Anish C ",
    Photo: "images/Members/Chakkirala Anish.jpg",
    Profile: "Web Dev",
    Year: "All",
    LinkedIn: "https://donothaveone.com",
    Github: "https://github.com/chakki1234",
    Website: "",
  },
  {
    id: "116",
    Name: "Anjaneya Tripathi",
    Photo: "images/Members/Anjaneya Tripathi.jpeg",
    Profile: "Web Dev",
    Year: "All",
    LinkedIn: "https://www.linkedin.com/in/anjaneya-tripathi-610234183/",
    Github: "https://github.com/AnjaneyaTripathi",
    Website: "",
  },
  {
    id: "117",
    Name: "Thrishik Senthilkumar",
    Photo: "images/Members/Thrishik Senthilkumar.jpg",
    Profile: "Web Dev",
    Year: "All",
    LinkedIn: "https://in.linkedin.com/in/thrishik-senthilkumar-123918176",
    Github: "https://github.com/thrishik7",
    Website: "",
  },
  {
    id: "118",
    Name: "Barath Kumar S",
    Photo: "images/Members/Barath.png",
    Profile: "Web Dev",
    Year: "All",
    LinkedIn: "https://linkedin.com/in/barath1999",
    Github: "https://www.github.com/barath99",
    Website: "https://barath99.github.io",
  },
  {
    id: "119",
    Name: "Smrithi Prakash",
    Photo: "images/Members/Smrithi.png",
    Profile: "Web Dev",
    Year: "All",
    LinkedIn: "https://linkedin.com/in/smrithi-prakash-452173193",
    Github: "https://github.com/Smrithi23",
    Website: "",
  },
  {
    id: "120",
    Name: "Jerry J",
    Photo: "images/Members/Jerry.png",
    Profile: "Web Dev",
    Year: "All",
    LinkedIn: "https://www.linkedin.com/in/jerry-j-89aa52174/",
    Github: "https://github.com/Hank-learner",
    Website: "",
  },
  // {
  //   id: "121",
  //   Name: "Rajat Bhatta",
  //   Photo: "images/Members/Rajat Bhatta.jpg",
  //   Profile: "Algos",
  //   Year: "All",
  //   LinkedIn: "https://www.linkedin.com/in/rajat-bhatta",
  //   Github: "https://github.com/barry-1928",
  //   Website: "",
  // },
  {
    id: "122",
    Name: "Mritunjay Kumar",
    Photo: "images/Members/Mritunjay Kumar.jpg",
    Profile: "Algos",
    Year: "All",
    LinkedIn: "https://www.linkedin.com/in/mritunjay-kumar-a5501b193/",
    Github: "https://github.com/mritunjay583",
    Website: "",
  },
  {
    id: "123",
    Name: "Kundan",
    Photo: "images/Members/Kundan Mandloi.jpg",
    Profile: "Algos",
    Year: "All",
    LinkedIn: "https://www.linkedin.com/in/kundan-mandloi-078627181/",
    Github: "https://github.com/Kunda31n",
    Website: "",
  },
  {
    id: "124",
    Name: "Harsh Bhadoria",
    Photo: "images/Members/Harsh Bhadoria.jpg",
    Profile: "Algos",
    Year: "All",
    LinkedIn: "https://www.linkedin.com/in/harsh-bhadoria-989665144/",
    Github: "https://github.com/harshbhadoria011",
    Website: "",
  },
  // {
  //   id: "125",
  //   Name: "Anukul Chand",
  //   Photo: "images/Members/Anukul Chand.jpg",
  //   Profile: "Algos",
  //   Year: "All",
  //   LinkedIn: "https://www.linkedin.com/in/anukul-chand-199369148/",
  //   Github: "https://github.com/cyberfreak5725",
  //   Website: "",
  // },
  // {
  //   id: "126",
  //   Name: "Shivani Chander",
  //   Photo: "images/Members/Shivani Chander.jpg",
  //   Profile: "Algos",
  //   Year: "All",
  //   LinkedIn: "https://www.linkedin.com/in/shivanichander/",
  //   Github: "https://github.com/shivanichander",
  //   Website: "",
  // },
  // {
  //   id: "127",
  //   Name: "Sandip Nair",
  //   Photo: "images/Members/Sandip Nair.jpg",
  //   Profile: "Algos",
  //   Year: "All",
  //   LinkedIn: "https://www.linkedin.com/in/sandipnair/",
  //   Github: "https://github.com/SanNare",
  //   Website: "https://medium.com/@sandipnr0",
  // },
  // {
  //   id: "128",
  //   Name: "Harshit Babbar",
  //   Photo: "images/Members/Harshit Babbar.jpg",
  //   Profile: "Algos",
  //   Year: "All",
  //   LinkedIn: "https://www.linkedin.com/in/harshit-babbar/",
  //   Github: "https://github.com/HarshitNITT",
  //   Website: "",
  // },
  // {
  //   id: "129",
  //   Name: "Rajiv",
  //   Photo: "images/Members/R Rajiv.jpeg",
  //   Profile: "Algos",
  //   Year: "All",
  //   LinkedIn: "https://www.linkedin.com/in/rajiv-ramachandran-51a510166/",
  //   Github: "https://github.com/rRajivramachandran",
  //   Website: "",
  // },
  {
    id: "130",
    Name: "Sri Harsha T.V",
    Photo: "images/Members/Sri Harsha T V.jpeg",
    Profile: "Algos",
    Year: "All",
    LinkedIn: "https://www.linkedin.com/in/sri-harsha-t-v-b7484a157",
    Github: "https://github.com/tvs1998",
    Website: "",
  },
  {
    id: "131",
    Name: "Shiwang Singh",
    Photo: "images/Members/Shivam Tiwari.jpg",
    Profile: "Algos",
    Year: "All",
    LinkedIn: "https://www.linkedin.com/in/shiwang-singh-33941515a",
    Github: "https://github.com/Shiwang9",
    Website: "",
  },
  {
    id: "132",
    Name: "Dhruv Bodani",
    Photo: "images/Members/Dhruv Bodani.jpg",
    Profile: "Algos",
    Year: "All",
    LinkedIn: "https://www.linkedin.com/in/dhruv-bodani-254a2b151",
    Github: "https://github.com/dB2510",
    Website: "",
  },
  {
    id: "133",
    Name: "Arvind Tatiparti",
    Photo: "images/Members/Arvind Tatiparti.jpg",
    Profile: "Algos",
    Year: "All",
    LinkedIn: "https://www.linkedin.com/in/arvindtatiparti/",
    Github: "https://github.com/r0uxt1",
    Website: "",
  },
  {
    id: "134",
    Name: "Aditya Kumar",
    Photo: "images/Members/Aditya Kumar.jpg",
    Profile: "Algos",
    Year: "All",
    LinkedIn: "https://linkedin.com/in/aditya-kumar-8218ab138",
    Github: "https://github.com/kumaraditya1999",
    Website: "",
  },
  {
    id: "135",
    Name: "Harshit Mogalapalli ",
    Photo: "images/Members/Harshit Mogalapalli.jpg",
    Profile: "Algos",
    Year: "All",
    LinkedIn: "https://www.linkedin.com/in/harshit-mogalapalli-44025917b",
    Github: "https://github.com/harshimogalapalli",
    Website: "",
  },
  {
    id: "136",
    Name: "Chidanand Dev Suryawanshi",
    Photo: "images/Members/Chidanand Dev Suryawanshi.jpg",
    Profile: "Algos",
    Year: "All",
    LinkedIn: "https://www.linkedin.com/in/engiiiiinerd",
    Github: "https://github.com/EngiiiiiNERD",
    Website: "",
  },
  {
    id: "137",
    Name: "Soham Roy",
    Photo: "images/Members/Soham Roy.jpg",
    Profile: "Algos",
    Year: "All",
    LinkedIn: "https://www.linkedin.com/in/sohamroy15",
    Github: "https://www.github.com/wolflegend99",
    Website: "",
  },
  {
    id: "138",
    Name: "Fasith",
    Photo: "images/Members/Fasith Ali.jpeg",
    Profile: "Algos",
    Year: "All",
    LinkedIn: "https://www.linkedin.com/in/fasith/",
    Github: "https://github.com/Fasith",
    Website: "",
  },
  {
    id: "139",
    Name: "Anoop Kumar",
    Photo: "images/Members/Anoop Kumar.jpg",
    Profile: "Algos",
    Year: "All",
    LinkedIn: "https://www.linkedin.com/in/anoop-kumar-51284514b/",
    Github: "https://github.com/kumaranoop900",
    Website: "",
  },
  {
    id: "140",
    Name: "Raj Kuvar Yadav",
    Photo: "images/Members/Raj Kuvar.jpg",
    Profile: "Algos",
    Year: "All",
    LinkedIn: "https://www.linkedin.com/in/raj-kuvar-4ba9b6172",
    Github: "https://github.com/RAJ107",
    Website: "",
  },
  {
    id: "141",
    Name: "Joel Antony Joseph",
    Photo: "images/Members/Joel Antony Joseph.jpg",
    Profile: "Algos",
    Year: "All",
    LinkedIn: "https://www.linkedin.com/in/joel-antony-joseph-97377315b/",
    Github: "https://github.com/JoAMD",
    Website: "",
  },
  {
    id: "141",
    Name: "Arvinth Saravanan",
    Photo: "images/Members/Arvinth Saravanan.jpg",
    Profile: "Algos",
    Year: "All",
    LinkedIn: "https://www.linkedin.com/in/arvinth-saravanan-3241b0192/",
    Github: "https://github.com/Arvinth-s",
    Website: "",
  },
  {
    id: "142",
    Name: "Harshit Agrawal",
    Photo: "images/Members/Harshit Agrawal.jpeg",
    Profile: "Algos",
    Year: "All",
    LinkedIn: "https://www.linkedin.com/in/harshit-agrawal-48b74a174/",
    Github: "https://github.com/HarshitCodex",
    Website: "",
  },
  {
    id: "143",
    Name: "Venkataraman V",
    Photo: "images/Members/Venkataraman V.jpeg",
    Profile: "Algos",
    Year: "All",
    LinkedIn: "https://www.linkedin.com/in/venkataraman-v-392090193/",
    Github: "https://github.com/Venkataraman8",
    Website: "",
  },
  {
    id: "144",
    Name: "Adithya K Krishna",
    Photo: "images/Members/Adithya Krishnakumar.jpg",
    Profile: "Algos",
    Year: "All",
    LinkedIn: "https://www.linkedin.com/in/adithya-krishnakumar-3a6087193/",
    Github: "https://github.com/AdithyaK243",
    Website: "",
  },
  {
    id: "145",
    Name: "Poorna Subramanian",
    Photo: "images/Members/Poorna subramanian.jpg",
    Profile: "Algos",
    Year: "All",
    LinkedIn: "https://www.linkedin.com/in/poorna-subramanian-90924b181",
    Github: "https://github.com/poorna20",
    Website: "",
  },
  {
    id: "146",
    Name: "Anagha Sethuraman",
    Photo: "images/Members/Anagha Sethuraman.jpg",
    Profile: "Algos",
    Year: "All",
    LinkedIn: "https://www.linkedin.com/in/anagha-sethuraman-192148179/",
    Github: "https://github.com/AnaghaSethuraman",
    Website: "",
  },
  // {
  //   id: "147",
  //   Name: "Senthur Raj",
  //   Photo: "images/Members/Senthur-Raj - Senthur raj.jpg",
  //   Profile: "Tronix",
  //   Year: "All",
  //   LinkedIn: "https://www.linkedin.com/in/imsenthur/",
  //   Github: "https://github.com/imsenthur",
  //   Website: "",
  // },
  // {
  //   id: "148",
  //   Name: "Shubham Saha",
  //   Photo: "images/Members/Shubham Saha.jpg",
  //   Profile: "Tronix",
  //   Year: "All",
  //   LinkedIn: "https://www.linkedin.com/in/shubhamsaha",
  //   Github: "https://github.com/Helinskii",
  //   Website: "",
  // },
  // {
  //   id: "149",
  //   Name: "Vibashan",
  //   Photo: "images/Members/Vibashan VS.jpg",
  //   Profile: "Tronix",
  //   Year: "All",
  //   LinkedIn: "https://www.linkedin.com/in/vibashan-vs-23321b142/",
  //   Github: "https://github.com/Vibashan",
  //   Website: "",
  // },
  // {
  //   id: "150",
  //   Name: "C Sundara Paripooranan",
  //   Photo: "images/Members/Sundara Paripooranan.jpg",
  //   Profile: "Tronix",
  //   Year: "All",
  //   LinkedIn: " https://www.linkedin.com/in/c-sundara-paripooranan-65343b15b",
  //   Github: "https://github.com/paripooranan",
  //   Website: "",
  // },
  // {
  //   id: "151",
  //   Name: "Abishek K R",
  //   Photo: "images/Members/Abishek K R.jpg",
  //   Profile: "Tronix",
  //   Year: "All",
  //   LinkedIn: "https://www.linkedin.com/in/abishek-ramachandran-81745b126",
  //   Github: "https://github.com/Abishek0398",
  //   Website: "",
  // },
  // {
  //   id: "152",
  //   Name: "D C Vivek",
  //   Photo: "images/Members/Vivek Dc.png",
  //   Profile: "Tronix",
  //   Year: "All",
  //   LinkedIn: "https://www.linkedin.com/in/vivek-dc-35069b141",
  //   Github: "https://www.github.com/dc28vivek",
  //   Website: "",
  // },
  // {
  //   id: "153",
  //   Name: "Abishek R",
  //   Photo: "images/Members/Abishek Rajasekaran.png",
  //   Profile: "Tronix",
  //   Year: "All",
  //   LinkedIn: "https://www.linkedin.com/in/abishek-r-468183178/",
  //   Github: "https://github.com/abishek27",
  //   Website: "",
  // },
  // {
  //   id: "154",
  //   Name: "Chockalingam",
  //   Photo: "images/Members/Chocka Lingam.jpg",
  //   Profile: "Tronix",
  //   Year: "All",
  //   LinkedIn: "https://www.linkedin.com/in/chocka-lingam-4bb803148",
  //   Github: "https://bitbucket.org/chocka/",
  //   Website: "",
  // },

  // {
  //   id: "155",
  //   Name: "Bhavya Krishna",
  //   Photo: "images/Members/Bhavya Krishna.jpg",
  //   Profile: "Tronix",
  //   Year: "All",
  //   LinkedIn: "https://www.linkedin.com/in/bhavya-krishna-6277b251",
  //   Github: "https://github.com/BhavyaKrishna",
  //   Website: "",
  // },
  // {
  //   id: "156",
  //   Name: "Aradhana M P",
  //   Photo: "images/Members/Aradhana M P.jpg",
  //   Profile: "Tronix",
  //   Year: "All",
  //   LinkedIn: "https://www.linkedin.com/in/aradhana-mohan-parvathy-64069413a/",
  //   Github: "https://github.com/MPARADHANA",
  //   Website: "",
  // },
  // {
  //   id: "157",
  //   Name: "Amritha S B",
  //   Photo: "images/Members/Amritha Bhaskaran.jpg",
  //   Profile: "Tronix",
  //   Year: "All",
  //   LinkedIn: "https://www.linkedin.com/in/amritha-s-b-43283015b",
  //   Github: "https://github.com/amritha-sb",
  //   Website: "",
  // },
  {
    id: "158",
    Name: "Mukesh Gandhi",
    Photo: "images/Members/Mukesh Gandhi.jpg",
    Profile: "Tronix",
    Year: "All",
    LinkedIn: "https://www.linkedin.com/in/mukesh-gandhi-8b7939128",
    Github: "https://github.com/MukkeshGandhi09",
    Website: "",
  },
  {
    id: "159",
    Name: "Aditya R",
    Photo: "images/Members/Aditya Ravi.jpg",
    Profile: "Tronix",
    Year: "All",
    LinkedIn: "https://www.linkedin.com/in/aditya-ravichander-b2584b178",
    Github: "https://github.com/adityaravichander",
    Website: "",
  },
  {
    id: "160",
    Name: "Akil M",
    Photo: "images/Members/Akil M.jpg",
    Profile: "Tronix",
    Year: "All",
    LinkedIn: "https://www.linkedin.com/in/akil-m/",
    Github: "https://github.com/akilm",
    Website: "",
  },
  {
    id: "161",
    Name: "Aditya Kumar Singh",
    Photo: "images/Members/Aditya Singh.jpg",
    Profile: "Tronix",
    Year: "All",
    LinkedIn: "https://www.linkedin.com/in/aditya-kumar-singh-645996152/",
    Github: "https://github.com/adityasingh3007",
    Website: "https://adityasingh3007.github.io/",
  },
  {
    id: "162",
    Name: "Raj Kumar Bhagat",
    Photo: "images/Members/Raj kumar.jpg",
    Profile: "Tronix",
    Year: "All",
    LinkedIn: "https://www.linkedin.com/in/raj-kumar-bhagat-97b310170/",
    Github: "https://github.com/Rajk0520",
    Website: "",
  },
  {
    id: "163",
    Name: "Kathirvel Rajan B",
    Photo: "images/Members/CBK - kathirvel rajan.jpeg",
    Profile: "Tronix",
    Year: "All",
    LinkedIn: "https://www.linkedin.com/in/kathirvelrajan22112002/",
    Github: "https://github.com/cbkathir",
    Website: "",
  },
  {
    id: "164",
    Name: "Ruphan S",
    Photo: "images/Members/Ruphan S.jpg",
    Profile: "Tronix",
    Year: "All",
    LinkedIn: "https://www.linkedin.com/in/ruphan-s-37412673",
    Github: "https://github.com/ruphan",
    Website: "",
  },
  {
    id: "165",
    Name: "Yash Patel",
    Photo: "images/Members/Yash Patel.png",
    Profile: "Tronix",
    Year: "All",
    LinkedIn: "https://www.linkedin.com/in/yash-patel-29379414a/",
    Github: "https://github.com/ComputerMaestro",
    Website: "",
  },
  {
    id: "166",
    Name: "Manu Aatitya R P",
    Photo: "images/Members/Manu Aatitya.jpg",
    Profile: "Tronix",
    Year: "All",
    LinkedIn: "https://www.linkedin.com/in/manu-aatitya-r-p-78457412b/",
    Github: "https://github.com/manuaatitya",
    Website: "",
  },
  {
    id: "167",
    Name: "Sudharsan S",
    Photo: "images/Members/Sudharsan Sundararaj.jpeg",
    Profile: "Tronix",
    Year: "All",
    LinkedIn: "https://www.linkedin.com/in/sudharsan-s-1a7a1317b/",
    Github: "https://github.com/sudharsan2000",
    Website: "",
  },
  {
    id: "168",
    Name: "S P Sharan",
    Photo: "images/Members/Sharan SP.jpg",
    Profile: "Tronix",
    Year: "All",
    LinkedIn: "https://www.linkedin.com/in/sharan-sp-05735a168",
    Github: "https://github.com/Syzygianinfern0",
    Website: "",
  },
  {
    id: "169",
    Name: "Anbuselvan D",
    Photo: "images/Members/Anbu Selvan.jpeg",
    Profile: "Tronix",
    Year: "All",
    LinkedIn: "https://ca.linkedin.com/in/anbu52",
    Github: "https://github.com/anbu52",
    Website: "",
  },
  {
    id: "170",
    Name: "Kumar Gaurav Singh",
    Photo: "images/Members/Gaurav Singh.jpg",
    Profile: "Tronix",
    Year: "All",
    LinkedIn: "https://www.linkedin.com/in/gaurav-singh-0b056117b",
    Github: "https://github.com/GauravSingh789",
    Website: "",
  },
  {
    id: "171",
    Name: "Kirthika Srinivasan ",
    Photo: "images/Members/Kirthika Srinivasan.jpg",
    Profile: "Tronix",
    Year: "All",
    LinkedIn: "https://www.linkedin.com/in/kirthika-srinivasan-6a9614181",
    Github: "https://github.com/kirthi-ka",
    Website: "",
  },
  {
    id: "172",
    Name: "Akshaya Subramanian",
    Photo: "images/Members/Akshaya Subramanian.jpeg",
    Profile: "Tronix",
    Year: "All",
    LinkedIn: "https://www.linkedin.com/in/akshaya-subramanian-a6a609185/",
    Github: "https://github.com/AkshayaCSubramanian",
    Website: "",
  },
  {
    id: "173",
    Name: "Miriam Santhosh Kadavan",
    Photo: "images/Members/Miriam.jpg",
    Profile: "Tronix",
    Year: "All",
    LinkedIn: "https://www.linkedin.com/in/miriam-santhosh-kadavan-30927a193/",
    Github: "https://github.com/Githubmsk",
    Website: "",
  },
  {
    id: "174",
    Name: "Jayamathangi Srinivasan",
    Photo: "images/Members/Jayamathangi Srinivasan.jpg",
    Profile: "Tronix",
    Year: "All",
    LinkedIn: "https://www.linkedin.com/in/jayamathangi-s-3464a8184",
    Github: "https://www.github.com/Jayamathangi",
    Website: "",
  },
  {
    id: "175",
    Name: "M Shyam",
    Photo: "images/Members/Shyam Murugan.jpg",
    Profile: "Tronix",
    Year: "All",
    LinkedIn: "https://www.linkedin.com/in/shyam-murugan/",
    Github: "https://github.com/shyam-king",
    Website: "",
  },
  {
    id: "176",
    Name: "Sachin Kumar",
    Photo: "images/Members/Sachin Kumar.jpg",
    Profile: "Tronix",
    Year: "All",
    LinkedIn: "https://www.linkedin.com/in/sachin-kumar-837b2b17b/",
    Github: "https://github.com/sachin-101",
    Website: "",
  },
  {
    id: "177",
    Name: "Rahul Bhope",
    Photo: "images/Members/Rahul Bhope.jpg",
    Profile: "App Dev",
    Year: "All",
    LinkedIn: "https://in.linkedin.com/in/rahul-bhope-3a0976130",
    Github: "https://github.com/rahulatulbhope",
    Website: "https://rahulatulbhope.github.io/",
  },
  {
    id: "178",
    Name: "Arijit Biswas",
    Photo: "images/Members/Arijit Biswas.jpg",
    Profile: "App Dev",
    Year: "All",
    LinkedIn: "https://www.linkedin.com/in/arijit-biswas-b7a85a98",
    Github: "https://github.com/arijitbiswasraj/",
    Website: "",
  },
  {
    id: "179",
    Name: "Disha Raj",
    Photo: "images/Members/Disha Raj.jpeg",
    Profile: "App Dev",
    Year: "All",
    LinkedIn: "https://www.linkedin.com/in/disha-raj-284a05116",
    Github: "https://github.com/DishaRaj",
    Website: "",
  },
  {
    id: "180",
    Name: "Shivam Tiwari",
    Photo: "images/Members/Shivam Tiwari.jpg",
    Profile: "App Dev",
    Year: "All",
    LinkedIn: "https://www.linkedin.com/in/shivam-tiwari-32018b175",
    Github: "https://github.com/shivamtiwari841797",
    Website: "",
  },
  {
    id: "181",
    Name: "Abhilasha Nagpal",
    Photo: "images/Members/Abhilasha_Nagpal - Abhilasha Nagpal.jpg",
    Profile: "App Dev",
    Year: "All",
    LinkedIn: "https://www.linkedin.com/in/abhilasha-nagpal",
    Github: "https://github.com/AbhilashaN",
    Website: "",
  },
  {
    id: "182",
    Name: "Rakesh Vaideeswaran",
    Photo: "images/Members/Rakesh Vaideeswaran.jpg",
    Profile: "App Dev",
    Year: "All",
    LinkedIn: "https://www.linkedin.com/in/rakesh-v-647481b6",
    Github: "https://github.com/RakeshVaideeswaran",
    Website: "",
  },
  {
    id: "183",
    Name: "Vaibhav Bairagi",
    Photo: "images/Members/Vaibhav Bairagi.jpg",
    Profile: "App Dev",
    Year: "All",
    LinkedIn: "https://www.linkedin.com/in/vaibhav-bairagi-a6ab97161",
    Github: "https://github.com/Vaibhavbairagi",
    Website: "",
  },
  {
    id: "184",
    Name: "Amogh J",
    Photo: "images/Members/Amogh Jahagirdar.jpg",
    Profile: "App Dev",
    Year: "All",
    LinkedIn: "https://www.linkedin.com/in/amoghjahagirdar/",
    Github: "https://github.com/amogh-jrules",
    Website: "https://amogh-jrules.github.io",
  },
  {
    id: "185",
    Name: "Nitin More",
    Photo: "images/Members/Nitin More.jpg",
    Profile: "App Dev",
    Year: "All",
    LinkedIn: "https://www.linkedin.com/in/nitin-more/",
    Github: "https://github.com/NitinMore7",
    Website: "",
  },
  {
    id: "186",
    Name: "Ark Srivastava",
    Photo: "images/Members/Ark  Srivatsvava.jpg",
    Profile: "App Dev",
    Year: "All",
    LinkedIn: "https://www.linkedin.com/in/ark-srivastava-252542160",
    Github: "https://github.com/rarsahki",
    Website: "",
  },
  {
    id: "187",
    Name: "Goutham C M",
    Photo: "images/Members/Goutham CM.jpeg",
    Profile: "App Dev",
    Year: "All",
    LinkedIn: "https://www.linkedin.com/in/goutham-c-m-5a0621154/",
    Github: "https://github.com/gouthamcm",
    Website: "",
  },
  {
    id: "188",
    Name: "Ayush Singh",
    Photo: "images/Members/Ayush Singh.jpg",
    Profile: "App Dev",
    Year: "All",
    LinkedIn: "https://www.linkedin.com/in/ayushsinghs/",
    Github: "https://github.com/ayush547",
    Website: "",
  },
  {
    id: "189",
    Name: "Naren Sairam",
    Photo: "images/Members/Naren Sairam.jpg",
    Profile: "App Dev",
    Year: "All",
    LinkedIn: "https://www.linkedin.com/in/naren-sairam-941739173",
    Github: "https://github.com/nsi319",
    Website: "",
  },
  {
    id: "190",
    Name: "Madhav Aggarwal",
    Photo: "images/Members/Madhav Aggarwal.jpg",
    Profile: "App Dev",
    Year: "All",
    LinkedIn: "https://www.linkedin.com/in/madhav-aggarwal-b16180181/",
    Github: "https://github.com/madhavaggar",
    Website: "",
  },
  {
    id: "191",
    Name: "Harshit Singh",
    Photo: "images/Members/Harshit Singh.jpg",
    Profile: "App Dev",
    Year: "All",
    LinkedIn: "https://www.linkedin.com/in/harshit-singh-83110a193/",
    Github: "https://github.com/LightHarshit",
    Website: "",
  },
  {
    id: "192",
    Name: "Khushali Patel",
    Photo: "images/Members/Khushali Patel.jpg",
    Profile: "App Dev",
    Year: "All",
    LinkedIn: "https://www.linkedin.com/in/khushali-patel-92b182179",
    Github: "https://github.com/khushali259",
    Website: "",
  },
  {
    id: "193",
    Name: "Isha Waghulde",
    Photo: "images/Members/Isha Waghulde.jpg",
    Profile: "App Dev",
    Year: "All",
    LinkedIn: "https://www.linkedin.com/in/isha-waghulde-4529aa17b",
    Github: "https://github.com/ishawaghulde.",
    Website: "",
  },
  {
    id: "194",
    Name: "S P Srinidhi",
    Photo: "images/Members/Srinidhi.jpg",
    Profile: "App Dev",
    Year: "All",
    LinkedIn: "http://www.linkedin.com/in/srinidhi-s-p-b005b4171",
    Github: "https://github.com/Srinidhi2000",
    Website: "",
  },
  {
    id: "195",
    Name: "Jack Samuel",
    Photo: "images/new-core/jack.jpg",
    Profile: "Tronix",
    Year: "All",
    LinkedIn: "https://www.linkedin.com/in/jacksamuel98/",
    Github: "",
    Website: "",
  },
  {
    id: "196",
    Name: "Jack Samuel",
    Photo: "images/new-core/jack.jpg",
    Profile: "Tronix",
    Year: "B tech 3rd Year",
    LinkedIn: "https://www.linkedin.com/in/jacksamuel98/",
    Github: "",
    Website: "",
  },
];
